### ISSUE TITLE
isModified not working properly.

### ISSUE THREAD

**Issue by m00nchile** [masumsoft/express-cassandra#100]
Steps to reproduce:
```javascript
// assume Test to be an initialized model
var test = new Test({ id: 0, data: "test" });
test.save(function(err) { console.log(test.isModified()) /* properly prints out false */});
test.data = "test2";
console.log(test.isModified()); /* properly prints out true */
test.save({ if_not_exist: true }, function(err) { console.log(test.isModified()) /* prints out false, even though data was not written to DB */});
```

Expected result:
isModified returns true after a save operation that failed a conditional check

Actual result:
isModified retuns false after a save operation that failed a conditional check

Version Info:
express-cassandra version 1.8.0

**Comment by masumsoft** [comment]
@pierreis if you have time, could you have a look at this?

**Comment by m00nchile** [comment]
Ah, I reversed the boolean values in Expected and Actual results. Edited the original message.

**Comment by pierreis** [comment]
The issue was caused by a missing test on save when the `if_not_exist` option is used.
I just created the pull request #101 fixing this issue, and added the adequate test to ensure it.
