### ISSUE TITLE
add scylladb support

### ISSUE THREAD

**Issue by phra** [masumsoft/express-cassandra#102]
hi,

when i try to use this orm with the [scylladb](http://www.scylladb.com/), that is a drop-in replacement for cassandra, the library throws an error stating `Keyspace system_schema does not exist`.

**Comment by pierreis** [comment]
ScyllaDB is *advertised* as a drop-in replacement for Cassandra 2.1.8. The version available in the master branch is targeted as Cassandra 3.x.

Did you use the right version?

**Comment by phra** [comment]
@pierreis didn't notice that, sorry!
