### ISSUE TITLE
Recursive read all models from expressCassandra.setDirectory

### ISSUE THREAD

**Issue by KARTIK01** [masumsoft/express-cassandra#104]
Currently only files present in particular folder given in  ```expressCassandra.setDirectory(path + '/models')```
read for models. if that folder contains nested folder and contains models those are not read  express-cassandra. In case of big project its hard to maintain all models in one single directory. So i [fork out](https://github.com/KARTIK01/express-cassandra) and solved this issue.
I will be happy to solved this for next version. Please consider it.

**Comment by masumsoft** [comment]
Fixed now in v1.8.2
