### ISSUE TITLE
Pagination not working for queries based on secondary indexes

### ISSUE THREAD

**Issue by adnan-kamili** [masumsoft/express-cassandra#105]
In case when primary key is not known, and query is done based on indexed fields only, the pageState is returned but it doesn't work properly. Always returns the same result set for limit 1 and repeats an item for limit >1.

```
getDataByQuery(query) {
	query.limit = query.limit || 1;
	const options = {
		fetchSize: parseInt(query.limit),
		pageState: query.nextPage,
		raw: true,
		allow_filtering: true
	};
	const dbQuery = {
		courseId: query.courseId,
		assignmentId: query.assignmentId
	}
	const rows = [];
	return models.instance.VisualClickstream.eachRowAsync(dbQuery, options, (count, row) => {
		rows.push(row);
	}).then((result) => ({
		rows: rows,
		nextPage: result.pageState
	}));
}
```

When the function is invoked with new pageState it again returns the same result set. The above code works only if query is done through the primary key (Id)

**Comment by adnan-kamili** [comment]
The issue doesn't replicate if we use https://github.com/datastax/nodejs-driver 
so the bug is with this ORM

**Comment by masumsoft** [comment]
Could you please provide a sample console.log output for the `options` object value before the `eachRowAsync` call where the pageState does not work?

**Comment by adnan-kamili** [comment]
pagestate works but it's result repeats last row as first row for each next page. So for fetchSize=1 it's stuck in a loop. The bug replicates in cassandra-driver as well as dse-driver. So the bug is not in the ORM.
