### ISSUE TITLE
Models are not loaded in unit testing

### ISSUE THREAD

**Issue by ehsun7b** [masumsoft/express-cassandra#108]
To reproduce:

a simple hello world app + express-cassandra + one simple model. It will work fine in dev mode. But in npm test using _chai_ cassandra can not load the models, although it finds the models directory correctly.

**Comment by masumsoft** [comment]
We are using express-cassandra with mocha tests without any issues. This module also has tests that works. It is very difficult to understand what went wrong in your case without further details from you. You may have a look at the tests section of this module for reference: https://github.com/masumsoft/express-cassandra/blob/master/test/test.js
