### ISSUE TITLE
Need to implement connection pooling with express-cassandra

### ISSUE THREAD

**Issue by pramod1792** [masumsoft/express-cassandra#110]
I am facing 'Connection refused' error whenever I apply load test. I could not find any configurations where connection pooling can be implemented.
I tried following configuration, there are no warnings with this, but looks like its not working and connection pooling is not getting applied

clientOptions: {
        contactPoints: [<host>],
        protocolOptions: { port: <port> },
        keyspace: "db",
        queryOptions: { consistency: Cassandra.consistencies.one },
        pooling: {
          coreConnectionsPerHost: {
            local : 5,
            remote : 5
          }
        }
    }

Please help

**Comment by masumsoft** [comment]
The clientOptions is passed as is to the dse-driver, so the pooling config should work. As per driver [docs](http://docs.datastax.com/en/developer/nodejs-driver/3.2/features/connection-pooling/) the pooling config should use the `distance` datatype like the following:

```
const models = require('express-cassandra');
const distance = models.datatypes.distance;

// ...
pooling: {
      coreConnectionsPerHost: {
        [distance.local] = 2,
        [distance.remote] = 1
      } 
   }

// ...
```
