### ISSUE TITLE
Add element in map is not working for variable in update api

### ISSUE THREAD

**Issue by vijayanjay** [masumsoft/express-cassandra#112]
Following is my code to add/append a element in map, were value is not substituted for key element.

```
var value_object = {email: user};//user is a variable which has string
models.instance.Person.update(value_object, {
contact_name:{'$add':{con_name:con_number}}//con_name and con_number is a variable which has aaa and 111 correspondingly.
 }, function(err){
 if(err) console.log(err);
 else{
 console.log('Updated contact inform in DB');
 }
 });
```

Output is:
======
| contact_name        |
+---------------------+
| {'con_name': '111'} |

why con_name is not substituted with the value present in that ?

**Comment by masumsoft** [comment]
This happened due to misconception about javascript object formation and not related to the ORM. If you want `con_name`'s value to be the key of the javascript object, then create the object like the following:

```
var value_object = { email: user };
var con_map = {};
con_map[con_name] = con_number;
models.instance.Person.update(value_object, {
    contact_name: {'$add': con_map}
}, function(err){
     if(err) console.log(err);
     else {
         console.log('Updated contact inform in DB');
     }
});
```
