### ISSUE TITLE
Add support for optimistic locking

### ISSUE THREAD

**Issue by adnan-kamili** [masumsoft/express-cassandra#113]
ORM should add support for optimistic locking to ensure updates are safe. Cassandra is designed for high volume data and it's common to run into issues while updating the record based on the stale copy.

**Comment by masumsoft** [comment]
Lightweight transactions supported by cassandra is already supported by the ORM. Could you give an example update operation you want to perform? What would be the raw cassandra query to do that update?

**Comment by adnan-kamili** [comment]
Consider following code snippet:

``` javascript
static async updateVisualDataById(req, res) {
	const model = await datalayer.getVisualDataById(req.params.id);
	if(!model) {
	  const message = `The visual data id - '${id}' does not exist`;
          throw new NotFoundError(message);
	}
	const updatedModel = req.body;
	// Check if recordingEndTime of new data is less than existing data
	let isStaleData = updatedModel.recordingEndTime < new Date(model.recordingEndTime).getTime();
	if (!isStaleData) {
		// Update the data in the database
		await datalayer.updateVisualDataById(id, updatedModel);
	}
        ...
}
```

Consider two requests R1 and R2 which are trying to update the same record with with id - id1. Due to network latency both the requests reach at almost same time.

R1 gets the current record:

const model = await datalayer.getVisualDataById(req.params.id);

This copy may get stale if R2 updates the table before R1 does, and hence overwrites the data. This issue was seen in our database records. R1 should never overwrite R2 because of stale data check, but if two requests are simultaneous the model copy of R1 can get stale and assume it's data is newer to current version.

So, if the version is added to the columns and updated on each UPDATE, the update query can add IF clause as mentioned in the following post:

https://www.safaribooksonline.com/library/view/learning-apache-cassandra/9781787127296/5e5991cb-eb1e-4459-9114-1d86e974e927.xhtml

**Comment by adnan-kamili** [comment]
LWT would fix my issue provided I can use a not equal comparator,

`const options = {conditions: {recordingEndTime : newRecordingEndTime }};`

In the above case, how can I specify LESS than operator

`IF recordingEndTime < newRecordingEndTime `

**Comment by adnan-kamili** [comment]
I debugged your code and it turns out you have hard-coded the equality operator. I changed it to LESS than operator and my problem was solved.

Can you please add support for mentioning operator in the 
`const options = {conditions: {recordingEndTime : newRecordingEndTime }};`
on priority. It's very crucial for our release.

Maybe new syntax could be:

`const options = {conditions: [ '$lte' : {recordingEndTime : newRecordingEndTime} ]};`

**Comment by masumsoft** [comment]
@adnan-kamili the fix is published into v1.9.0

You can now use any query operator with the update conditions. Also the $ne (!=) operator is now supported for IF conditions.

**Comment by adnan-kamili** [comment]
Thanks a lot for such a great support.

**Comment by adnan-kamili** [comment]
If existing value in database is null, and on update, check is against timestamp, then the less than condition fails.

**Comment by masumsoft** [comment]
@adnan-kamili could you get the query generated by the ORM by setting the `DEBUG=express-cassandra` environment variable while starting your app and compare it to the expected query you want?

**Comment by adnan-kamili** [comment]
It crashes before the query is generated:

const options = {conditions: {recordingEndTime : { '$lte' :model. recordingEndTime} }};

Invalid Value: "[object Object]" for Field: recordingEndTime (Type: timestamp)

**Comment by masumsoft** [comment]
What does the `model.recordingEndTime` contain? For a timestamp field it should contain a javascript Date object according to this table: http://express-cassandra.readthedocs.io/en/latest/datatypes/#cassandra-to-javascript-datatypes

**Comment by adnan-kamili** [comment]
Timestamp is a number so we always pass a number, 20 is a valid timestamp number. It works if recordingEndTime has some value initially in the database, but fails if updated value is null in the database.

**Comment by adnan-kamili** [comment]
The query fails in datastax devcenter too

**Comment by masumsoft** [comment]
Looks like an issue with cassandra and not particularly an issue with the ORM itself. 

Though it's not logical to compare a value with a null attribute and the transaction operation should not be applied in such cases in my opinion, and testing a sample query in my end didn't through any errors in cassandra 3.9, and as expected, the transaction was not applied. 

But anyways, you could always create an issue with the cassandra issue tracker with your query and table structure.
