### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by tybeck** [masumsoft/express-cassandra#114]
When using hooks; if you ADD additional data after instantiating the model, express-cassandra does not pick these up; it ignores them.

**Comment by masumsoft** [comment]
Could you provide an example? What do you mean by ADD additional data?

**Comment by jdm470** [comment]
I'm seeing the same behavior.  If I set any values in the before_save hook, they are not actually getting saved to cassandra.  The instance variable is getting updated, but the value is never making it to cassandra.

**Comment by jdm470** [comment]
FWIW, I'm seeing the opposite behavior with default values in the model.  For example, if I set a default string to static text, the value makes it to the database, but the instance variable is not updated.

I'm just looking for something that will set default values, update the instance variable so I know what the values are, and successfully run the validation.  Outside of doing it myself before calling the save, I haven't figured out a way yet.

**Comment by masumsoft** [comment]
hooks api will have some breaking changes in the api in upcoming v2.0.0, this issue should be gone in the next release.

**Comment by masumsoft** [comment]
Hooks api has breaking changes in v2.0.0

http://express-cassandra.readthedocs.io/en/stable/management/#hook-functions
