### ISSUE TITLE
Multiple Key Spaces Support

### ISSUE THREAD

**Issue by contactakagrawal** [masumsoft/express-cassandra#115]
Hi, Right now we have a way to provide single key space per express-cassandra, we have to create multiple express-cassandra instances for each key space if we want to support multiple key spaces in my application
Please let me know if single express-cassandra instance can support multiple key spaces which I am not aware of.
Please correct me if I am missing anything here.

**Comment by masumsoft** [comment]
Yah, right now multiple keyspaces are not supported by the models, but you could work around it by using multiple instances. Providing support for a keyspace_name option in the model definition is planned. But not implemented yet.

I'll keep this open for now. Will try to implement it if I get some time, PRs are also welcome.

**Comment by contactakagrawal** [comment]
thank you, meanwhile I am using the work around, will surely send the PR if able to work on that, just wanted to check that express-cassandra fires few queries at the startup like 
SELECT * FROM system_schema.columns WHERE table_name = ? AND keyspace_name = ?; with params: ["employee","ABC"]
and then throws error ERROR 2017-07-17 07:17:34.039 UTC uncaughtException: Error while retrieveing Schema of DB Table "ResponseError: Keyspace system_schema does not exist"

Can you please explain what does this mean or if I am missing anything here.

Thank you again for such a nice framework :)

**Comment by masumsoft** [comment]
closing as duplicate to #98
