### ISSUE TITLE
set write and read different consistency level 

### ISSUE THREAD

**Issue by manoj-compro** [masumsoft/express-cassandra#116]
I want to set read and write consistency level both different.
Read consistency: 1
Write consistency: 2
I know one of way setting consistency using client options while initialization but is there a way so can set write consistency while querying.

 clientOptions: {
            contactPoints: ['127.0.0.1'],
            protocolOptions: { port: 9042 },
            keyspace: 'mykeyspace',
            queryOptions: {consistency: models.consistencies.one} 
        },

**Comment by masumsoft** [comment]
Every query has a configurable consistency parameter by using the options object. By default, the initial `queryOptions` is used and every find, save, update, delete query can overwrite the defaults. For example, to overwrite the consistency of a find query:

```js
models.instance.Person.find({name: 'John'}, {consistency: models.consistencies.quorum}, function(err, people){
    
});
```
