### ISSUE TITLE
Migration alter and drop not working

### ISSUE THREAD

**Issue by Hristijan95** [masumsoft/express-cassandra#117]
Migration alter and drop are not working. I am getting the following error:

`apollo.model.tablecreation.dbcreate: Error while creating DB Table -> ResponseError: line 1:88 mismatched input ',' expecting '<' (..."userId" uuid , "photosIds" set [,]...)`

**Comment by masumsoft** [comment]
Could you please share your model definition?

**Comment by Hristijan95** [comment]
After a while, realized that the problem is with the model definition, but I have no idea why. The set type is not working. Here is the model definition:

> module.exports = {
    fields: {
        id: {type: 'uuid', default: {"$db_function": "uuid()"}},
        userId: {type: 'uuid', rule: {required: true}},
        photos: {type: 'set', rule: {required: true}},
        created: {type: "timestamp", default: {"$db_function": "toTimestamp(now())"}}
    },
    key: [['id'], 'created']
};

There is something wrong with the set type field (photos).

**Comment by masumsoft** [comment]
The set type requires a typeDef to let cassandra know what type of data will there be in the set. Have a look at the docs to see how to define collection datatypes (list, set, map etc.): http://express-cassandra.readthedocs.io/en/latest/advanced/#collection-data-types
