### ISSUE TITLE
License conflict

### ISSUE THREAD

**Issue by KararTY** [masumsoft/express-cassandra#122]
Hey there, just wanted to point out that since this uses the dse-driver, there might be license conflict for those who aren't DataStax Enterprise customers.

Is it fine to use Express-Cassandra without a Datastax Enterprise license?

**Comment by masumsoft** [comment]
Oh good catch! I didn't notice dse-driver license does not allow connecting to apache cassandra! I'm going to use cassandra-driver as default then and only use dse-driver if already installed. Will be fixing this conflict in the next release asap.

**Comment by masumsoft** [comment]
Fix is released in v1.10.0

dse-driver is now removed. Datastax Enterprise users now need to install dse-driver along with express-cassandra. If dse-driver is found installed, the module will use that, otherwise the module will be using the cassandra-driver by default.
