### ISSUE TITLE
Insert performance?

### ISSUE THREAD

**Issue by jcbarton** [masumsoft/express-cassandra#123]
Hi,

More of a question about where I'm going wrong really.

So, we're looking to use Cassandra - and I've been playing with importing some of our existing data.

If I use the "raw" data-stax nodejs [driver](https://github.com/datastax/nodejs-driver) then  I can import my 350k sample records at ~26k/sec into my local cassandra docker.

I then used this ORM, and I get ~4k/sec.

I'm using "doBatch" and batching and uploading in a similar way to my "raw" approach. (same batch size + same number of parallel operations).

Is there any reason why it is so much slower - or rather, what can I do to speed up inserts using express-cassandra!

**Comment by masumsoft** [comment]
Could you share both approach here? The exact code you used in both cases would help me deduce the reason behind the slow insert rate.

**Comment by jcbarton** [comment]
Certainly! Thanks for taking the time to help.

Approach using the data-stax npm package (relevant code included)
`
var cassandra = require('cassandra-driver');
 var client = new cassandra.Client({ contactPoints: ['127.0.0.1'], keyspace: 'test' });
//generate queries. each looks similar to:
//let query = "INSERT INTO test.XXX (a,b,c);
//let params = [x,y,z];
//queries.push({
//                query: query,
//                params: params
//            });

//create batches of inserts.. then use async:
 async.eachLimit(chunks, 30, (chunk, chunkCallback) => {
                client.batch(chunk, { prepare: true }, chunkCallback);
            }, (err: Error) => {

`
Approach using express-cassandra
`
 var Cassandra = require('express-cassandra');
        var client = Cassandra.createClient({
            clientOptions: {
                contactPoints: ['127.0.0.1'],
                protocolOptions: { port: 9042 },
                keyspace: 'test',
                queryOptions: { consistency: Cassandra.consistencies.one }
            },
            ormOptions: {
                defaultReplicationStrategy: {
                    class: 'SimpleStrategy',
                    replication_factor: 1
                },
                migration: 'safe',
                createKeyspace: true
            }
        });

 await client.connectAsync();
//load my schemas...
// await client.loadSchemaAsync(tableName, data);

//create batches of records using documented approach  :

 async.eachLimit(chunks, 30, (chunk: BaseModel[], chunkCallback) => {
let batch = [];
 for (let i = 0, j = chunk.length; i < j; i++) {
    let cassandraRecord = new client.instance.XXX(chunk[i]);
    let cassandraInsert = cassandraRecord.save({ return_query: true });
     batch.push(cassandraInsert);
}
 client.doBatch(batch, chunkCallback);

`

Hopefully it's clear enough what I'm doing - if you need some more information please let me know.

BTW - I've written the start of a TypeScript decorators package. This allows you to create schemas using decorators in a similar way to [sequalize-typescript](https://github.com/RobinBuschmann/sequelize-typescript)
`
@Table({ key: [["UserId"], "OrderTime"] })
export class useridordertime extends BaseModel {
    @Column
    public UserId: string;
    @Column
    public OrderTime: string;
}
`

Very early days - but it already creates the schema to use in "loadSchema" calls - and allows me to work with typed models. If there is some interest I'll try to get our company to open source it.

**Comment by jcbarton** [comment]
Hi again,

I did some more analysis of where the time is being spent today.

So - if I use express-cassandra to create the connection; create my queries myself and then use the raw execute_batch I get approximately the same performance as the data-stax driver. (As you would expect).

Contrast this (15s for 375l records) to the following timings using the approach [here](http://express-cassandra.readthedocs.io/en/latest/batch/)

creating "new" records: 15s
calling save with "return_query: true": 19s
uploading using doBatch: ~60s

Looking at what it does, I can see its doing a lot of extra work (as it would have to!). Would you expect such a difference in performance?

In your opinion what is the optimal way to insert a large number of records using express-cassandra?

**Comment by masumsoft** [comment]
The numbers look interesting, I'll do a profile (when I get some time) to find out why it's happening. Btw, how much time it takes for your code to generate the queries? I guess the `15s` time is for the `execute_batch` only right?

**Comment by jcbarton** [comment]
Yes, for the "raw" data-stax approach that takes 15s - i've already looped over the data and created the data (such as):
{
query: 'INSERT INTO test.XXX (UserId, OrderTime) VALUES(?, ?);";
params: [x,y]
}

I then just batch them up and call "client.batch" on the data-stax driver - or "execute-batch" when I tested it using express-cassandra.


For the full express cassandra, the time includes doing each of the 3 steps from your "batch doccumentation" page. For each of my models, I have to create a "new" object, then call "save" and then finally I batch them up and call "doBatch".

One thought I had was that I could add an extra function or 2 that does a lot less checking etc, and creates me the raw {query,params} objects so I can then do an execute_batch.

I've forked the project so I'll look into the project in more detail and see what I can come up with!

Thanks again for taking the time to respond.

**Comment by masumsoft** [comment]
Did some profiling today and discovered [hooks](http://express-cassandra.readthedocs.io/en/latest/management/#hook-functions) to be the bottleneck here. Most of the time is spent in processing before and after hook function calls for large datasets after batch is done.

Hooks implementation keeps a generic hook if none is defined and it needs to be changed due to this performance issue. Also docs needs to be updated with a warning to performance problems if hooks is used.

**Comment by masumsoft** [comment]
Insert performance for orm batches has been improved in v2.0.0
