### ISSUE TITLE
ResponseError: Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset. See innerErrors.]

### ISSUE THREAD

**Issue by Shivagoy** [masumsoft/express-cassandra#125]
ResponseError: Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset. See innerErrors.]

**Comment by Shivagoy** [comment]
I am using  "express-cassandra": "^1.10.0",  "dse-driver": "^1.3.1",

**Comment by masumsoft** [comment]
Please use dse-driver ~1.2.0 for now.

1.3.x has backwards incompatible changes and is not fully compatible with express-cassandra as of now. Will be updating the doc to reflect this.

**Comment by masumsoft** [comment]
updated docs already, so closing it now
