### ISSUE TITLE
Unit testing model operations without connecting to DB

### ISSUE THREAD

**Issue by simonholmes** [masumsoft/express-cassandra#127]
I'm trying to unit test my app controllers with Mocha, Chai and Sinon, but am having troubles stubbing and spying express-cassandra. I had the tests working fine when using MongoDB & Mongoose, but the model generation and approach to references seems to be different here.

From looking at the source code, `models.instance` is generated when a model is compiled. I can't see how to compile a model without creating a database connection, and Sinon can't add a stub to `.instance` as it doesn't exist if a model isn't compiled.

It's important to be able to test without a DB connection, as unit tests run in our CI framework with no access to our database tiers.

Given the simplified controller below, is there a way to stub out `models.instance.Conversations`? Or to compile the `Conversations` model with creating a DB connection?

```javascript
const models = require('express-cassandra');

const addToConversation = function (formId) {
  const newDetails = {
    formId : formId
  };
  const newForm = new models.instance.Conversations(newDetails);
  newForm
    .saveAsync({
      ttl : 7 * 24 * 60 * 60
    })
    .then(() => {
      console.info('Form lookup created', newDetails.formId);
    })
    .catch((err) => {
      console.error('Error creating form lookup', err);
    });
};
```

Thanks!

**Comment by masumsoft** [comment]
v2.0.0 contains changes where you no longer need to syncDB to get the model instances. The [v2 docs](http://express-cassandra.readthedocs.io/en/stable/usage/#alternatively-load-organize-models-yourself) contain the usage of alternative load schema system where syncDB method needs to be separately called when required. I hope this might fix the issue you were facing, please let me know if you still face the same problem.

**Comment by masumsoft** [comment]
Closing this as dormant, feel free to open it if the problem persists.
