### ISSUE TITLE
UDT (User Defined Types) schema mismatch

### ISSUE THREAD

**Issue by ahmedosama94** [masumsoft/express-cassandra#128]
When using a user defined type, the first time the table is created, express-cassandra handles it smoothly, but when the table is already created there is always an apollo.model.tablecreation.schemamismatch error thrown, and then it attempts to drop and recreate the column.

**Comment by ahmedosama94** [comment]
Gives this message on each run (migration set to alter), if it is helpful:
model schema for table "table" has new incompatible type for field "field"

**Comment by ahmedosama94** [comment]
@masumsoft I found the issue to be using FROZEN in uppercase in the set's typeDef, solved the issue by changing (typeDef: "<FROZEN<log_entry>>") to (typeDef: "<frozen<log_entry>>")

**Comment by masumsoft** [comment]
@ahmedosama94 thanks for the update, though I didn't have much time to fix this issue yet, your findings would definitely help dig out the problem faster. Current version 2 milestone has a lot of new things in progress and I'm hopeful it would be resolved soon with the 2.0.0 release. For now use lowercased definitions.
