### ISSUE TITLE
Best practice for opening connections/what happens in .connect() event

### ISSUE THREAD

**Issue by deejbee** [masumsoft/express-cassandra#131]
Apologies if this is the wrong place to ask questions.  I can ask move it to SO if preferred.

I can't see a working best practice example where `createClient()` should be located.  I have encapsulated the function into a re-usable module and it fires the `.connect` event for each of the 10 tables I have set up, and I see 10 firings of that event, I think after loading the schema for each.

Suppose I have 10 tables, does that mean express-cassandra has created 10 persistent connections or does it work in a different way?  Should I be calling Cassandra.createClient() on every request?

Thanks

**Comment by masumsoft** [comment]
`createClient()` should be called once, for example while your application is initializing. Ideally you should load all your schema / models once and then reuse the instances in other places of your app. So in your module, you may have an init function that is called once while the app starts up and export the returned variable from the `createClient()`, so you could require and reuse it from other places.

Connections to cassandra are automatically handled by express-cassandra. When your app initializes a schema, it creates a connection per schema to make sure your defined model and the corresponding cassandra table schema are in sync and does necessary migrations if needed and `immediately shutdown the client` after migrations are done. After your app successfully initializes, then a single connection per cassandra node in the cluster is maintained for handling queries. The underlying driver uses the same connection for all queries and reconnects automatically if the connection is lost.
