### ISSUE TITLE
Schema for table changed, alter migration not possible, drop table? (y/n)

### ISSUE THREAD

**Issue by Rubatharisan** [masumsoft/express-cassandra#138]
Constantly asks me to drop the table, when the fields havn't changed.
Following is my fields:

> fields:{

        bids: {
            type: "frozen",
            typeDef: "<list<map<varchar, float>>>"
        },
},

Can anybody enlighten me, if it's me who is doing it wrong?

**Comment by masumsoft** [comment]
This seems to be a bug in the parser as cassandra converts the typeDef to `<list<frozen<map<varchar, float>>>>`, so a workaround for now would be to define bids like this:

```
bids: {
    type: 'frozen',
    typeDef: '<list<frozen<map<varchar, float>>>>'
},
```

**Comment by Rubatharisan** [comment]
Thank you @masumsoft, sorry for the late reply! :)
