### ISSUE TITLE
How to set compression properties in a table schema 

### ISSUE THREAD

**Issue by hiteshdua1** [masumsoft/express-cassandra#139]
Hi @masumsoft ,

I was wondering , how to define the compression properties in express-cassandra. 

I had searched through the document for the same 
link : http://express-cassandra.readthedocs.io/en/latest/schema/ 

But could not find a way to do it, 

Could you please proivde a source for the same or tell me how to go about it ?

**Comment by masumsoft** [comment]
Setting table properties is not yet implemented, you need to manually set them from cql as of now. A pending issue to allow setting table properties is already there, so closing as duplicate of #45
