### ISSUE TITLE
Replication factor is getting updated in production environment as well. Please confirm if this is a feature or bug

### ISSUE THREAD

**Issue by gitmnikhil** [masumsoft/express-cassandra#140]
Hi @masumsoft ,

When we change the replication factor in express cassandra and deploy the application in production environment the replication factor is updated in production db servers as well. 
Please confirm if it is a desired feature or a bug.

**Comment by masumsoft** [comment]
Yah this is expected, as you might want to change the replication factors in production, this is the expected behaviour.
