### ISSUE TITLE
Paging in cassandra

### ISSUE THREAD

**Issue by measwel** [masumsoft/express-cassandra#141]
Dear Masum,

I would like to implement paging in my web app. I would like to supply the page number and number of records to retrieve. Is this possible? What is the best way to implement it? 

If I have many users in my db, then the admin should be able to retrieve only a subset, lets say 10 users per page and be able to browse the total set by paging. Is this possible?

**Comment by masumsoft** [comment]
Pagination is a bit tricky in cassandra. I would suggest to read the [paging docs for cassandra](https://docs.datastax.com/en/cql/3.3/cql/cql_using/useToken.html) to get a grasp of why. In fact jumping to a random page number is a costly operation even in databases that supports it and if not sharded properly, it can slow down everything.

Cassandra provides support for a token based pagination system, where to get the next page of results you need to create a token from the last element of the current page. You cannot directly skip to the 10th page for example. To implement token based pagination, use the [express-cassandra token pagination](http://express-cassandra.readthedocs.io/en/stable/find/#find-token-based-pagination) docs.

Another way is to use the nextPage / pageState property streaming. To implement it: use the [express-cassandra streaming pagination](http://express-cassandra.readthedocs.io/en/stable/find/#find-fetching-large-result-sets-using-streaming-queries) docs.

**Comment by measwel** [comment]
Again; thank you very much Masum! I will analyse the possibilities you have mentioned.
