### ISSUE TITLE
Global filtering

### ISSUE THREAD

**Issue by sureshvarman** [masumsoft/express-cassandra#145]
Hi,
I'm new to cassandra, and im trying to do an multi-tenant MVP using nodejs, Is there any way to apply global filtering in express-cassandra, where i can apply my filtering at the middleware level with the help of user token and express-cassandra model object.

Thanks in advance :)

**Comment by masumsoft** [comment]
Sorry for being so late to answer this. I was kind of inactive with this project for several months.

Nope express-cassandra does not have any built in support for multi-tenant systems. You have to handle this in the application itself.
