### ISSUE TITLE
$add and $remove in the same query for sets.

### ISSUE THREAD

**Issue by Rubatharisan** [masumsoft/express-cassandra#152]
Hi masumsoft 👍,

I am trying to flush all elements in a set, and then add new elements to it with the ".update" method. How do I do that?

**Scenario**
TABLE: users
Columns: | username | pets |
Types: I text | collection(set) | 

Current entry: 
username: ruba
pets: ['dog', 'cat', 'elephant']

`models.instance.Users.update({username:ruba}, {
    pets:{'$add': ['dog', 'cat', '**elephant**']},
}, function(err){
    if(err) throw err;
    done();
});`

In reality, I would like to do: 
`models.instance.Users.update({username:ruba}, {
    pets:['dog', 'cat', '**ape**'],
}, function(err){
    if(err) throw err;
    done();
});`
To replace the already existing set with the new set.

Or more like: 
`models.instance.Users.update({username:ruba}, {
    pets:{'
           $remove: ['**elephant**'],
           $add: ['**ape**']
    },
}, function(err){
    if(err) throw err;
    done();
});`

Is there any way to accomplish this (without using the .save method); ?

**Comment by Rubatharisan** [comment]
Me, not, functioning on mondays - basically. 
Solved 👍

**Comment by masumsoft** [comment]
Well, it looks like your desired functionality is already there. Did the documentation confused you in any way? Let me know if you think any clarification in the docs was required.

**Comment by Rubatharisan** [comment]
No it is just me who was overthinking a very simple thing. 
The docs are fine 👍
