### ISSUE TITLE
Validation error not printed to console

### ISSUE THREAD

**Issue by measwel** [masumsoft/express-cassandra#154]
In parser.js, line 99:
`throw buildError('model.validator.invalidvalue', validationMessage(fieldValue, fieldName, fieldType));`

Does not print the fieldValue, fieldName and fieldType to the console. I have to manually output them to know which validation failed. 

Am I missing a setting?

**Comment by masumsoft** [comment]
The tests have this error message properly printed with values. Could you please provide your model and example data to reproduce this?

**Comment by masumsoft** [comment]
Closing this as it cannot be reproduced. Will re-open if valid data and steps are provided to reproduce it.
