### ISSUE TITLE
UDF & UDA with more than one parameter not working properly

### ISSUE THREAD

**Issue by erltrax** [masumsoft/express-cassandra#155]
I defined an aggregate with two parameters, I can query it like the one below without any issues...
```
SELECT aggregate1(param1, param2) FROM materializedView1 WHERE key1='ID-111' AND key2='ID-222';
```

I tried to do the same inside an app. The code looks like:
```
...
const query = {
   key1: 'ID-111',
   key2: 'ID-222'
};

const options = {
   select: ['aggregate1(param1, param2)'],
   materialized_view: 'materializedView1'
};

model.instance.find(query, options, function(err, result) {
...
});
```

Instead of calling the aggregate function, the result looks like it was called as if the `options.select` was set to `['*']`.
I modified my aggregate so that it will only take in one parameter and everything worked as expected.

Is this a configuration issue (perhaps I missed something out) or is it possible that the current implementation does not support aggregate functions with more than one parameter?

I am using version **_3.10.10_**

**Comment by masumsoft** [comment]
Fixed in v2.2.2
