### ISSUE TITLE
Getting timeout errors while indexing many tables

### ISSUE THREAD

**Issue by jimmibond** [masumsoft/express-cassandra#156]
Hi,

I am getting timeout error for apollo.model.tablecreation.dbindexcreate and some time dbtable create.

```
apollo.model.tablecreation.dbindexcreate: Error while creating index on DB Table -> NoHostAvailableError: All host(s) tried for query failed. First host tried, 127.0.0.1:9042: OperationTimedOutError: The host 127.0.0.1:9042 did not reply before timeout 12000 ms. See innerErrors
```

after few restarting nodejs few times, all tables are created in Cassandra and getting initialized perfectly. 

I am having around 40 models, in each restart, I can see few models getting initialized after 4 to 10 restarts everything works perfectly.

version: 2.1.1 
nodejs 8.9.1
cassandra : 3.9

Please help me to resolve this issue.

thanks,
Jimmi

**Comment by masumsoft** [comment]
looks like it's taking more time to complete the indexing than the timeout specified in your cassandra config, you may have a look at `request_timeout_in_ms` in your cassandra.yml file.

**Comment by masumsoft** [comment]
Ok it also might happen due to the nodejs-driver default timeout being 12000ms. You may use any of the clientOptions mentioned in the [nodejs-driver docs](https://docs.datastax.com/en/developer/nodejs-driver/3.3/api/type.ClientOptions/) in express-cassandra clientOptions parameter.

also it looks like the setting you want to overwrite is socketOptions.readTimeout since it has a 12000ms default timeout.

**Comment by jimmibond** [comment]
Thank you for your comment, I did that made socketOptions.readTimeout to 0 in nodejs-driver file and it worked. but not able to set this parameter from client configuration.

**Comment by masumsoft** [comment]
How do you load your models? Could you share the code you use to load your models? For example, if you are binding a models directory, then you would do something like this:

```
models.setDirectory( __dirname + '/models').bind(
    {
        clientOptions: {
            contactPoints: ['127.0.0.1'],
            protocolOptions: { port: 9042 },
            keyspace: 'mykeyspace',
            queryOptions: { consistency: models.consistencies.one },
            socketOptions: { readTimeout: 0 }
        },
        ormOptions: {
            defaultReplicationStrategy : {
                class: 'SimpleStrategy',
                replication_factor: 1
            },
            migration: 'safe'
        }
    },
    function(err) {
        if(err) throw err;
    }
);
```

If you want to disable the timeout only for loading models, then you may create multiple instances of express cassandra with different timeout configurations.

**Comment by ahmedosama94** [comment]
@masumsoft This has been bugging me for ages, and I could not figure out the solution, thank you.
