### ISSUE TITLE
Requires model to be recreated on every process restart despite of any changes.

### ISSUE THREAD

**Issue by amulyakashyap09** [masumsoft/express-cassandra#158]
Every time server/pm2 restarts syncing needs model to be dropped and recreated despite any changes. And it happens randomly for some collections only.

**Comment by masumsoft** [comment]
@amulyakashyap09  It's hard to guess what's happening with your particular setup without information about your models and how they are loaded, what's your migration configuration, what version you are using etc.

**Comment by masumsoft** [comment]
Closing as no further response was received.
