### ISSUE TITLE
[Question] How can I wrap the createClient and returned object in a module?

### ISSUE THREAD

**Issue by Extarys** [masumsoft/express-cassandra#159]
I do know this is not a specific issue with this module. I'm sorry.
I would like to clean up me server.js file by making the cassandra stuff in an external file
I tried for hours to make this works but I can't - StackOverflow wasn't helpful. I'd appreciate some help if someone got time.

```
	var models = ExpressCassandra.createClient({
	    clientOptions: {
	        contactPoints: config.cassandra.servers,
	        protocolOptions: { port: 9042 },
	        keyspace: 'mylilthing',
	        queryOptions: {consistency: ExpressCassandra.consistencies.quorum}
	    },
	    ormOptions: {
	        defaultReplicationStrategy : {
	            class: 'NetworkTopologyStrategy',
	            'DC1': 3
	        },
	        migration: 'alter', 
	    }
	});
	// TODO: Should load files from ./ except index.js
	var MyModel = models.loadSchema('Logs', {
	    fields:{
	        logId     : "timeuuid",
	        category  : "text",
	        createdAt : "timestamp",
	        message   : "text"
	    },
	    key:["logId"]
	});
	console.log(models)
	module.export =  models;

```

The model from the console log is populated but when I import it on my server.js the object is empty.
Any idea how I can make this works?

Thanks :smile:

**Comment by masumsoft** [comment]
Though it's a late response, I guess it might be helpful. You need to wait for the models to load in your application startup before starting to use them. For example, you could have your web app routes register after the models are loaded. For your case you are missing the syncDB call like the following:

```
MyModel.syncDB(function (err, result){
    // Now the model is loaded, so you can have your app initialize it's routes.
});
```
