### ISSUE TITLE
Migrations throws exception when table has collection of UDTs

### ISSUE THREAD

**Issue by vgjenks** [masumsoft/express-cassandra#166]
Using latest driver w/ Cassandra 3.11. Node 9.8.0. No scripting of tables or UDTs - just allowing express-cassandra to generate everything.

express-cassandra configuration:

```
const models = require("express-cassandra");
const types = require("cassandra-driver").types;

const udts = {
	role_permission: {
		permission_name : "text",
		permission_friendly_name : "text",
		permission_descr : "text",
		status_flag : "int"
	}
}

const loadDbConnectionPool = () => {
	return new Promise((resolve, reject) => {
		models.setDirectory(__dirname.replace("data", "model")).bind({
			clientOptions: {
				contactPoints: ["127.0.0.1"],
				protocolOptions: { port: 9042 },
				keyspace: "my_admin",
				queryOptions: { consistency: models.consistencies.one },
				pooling: {
					coreConnectionsPerHost: {
						[types.distance.local]: 3,
						[types.distance.remote]: 1
					} 
				},
			},
			ormOptions: {
				createKeyspace: true,
				createTable: true,
				defaultReplicationStrategy: {
					class: "SimpleStrategy",
					replication_factor: 1
				},
				migration: "safe",
				udts: udts
			}
		},
		err => {
			if (err) {
				reject(err);
			}
			resolve();
		});
	});
};

module.exports = loadDbConnectionPool;
```

Mapping to table (user_profileModel.js):

```
module.exports = {
    fields: {
		user_profile_id: "text",
		first_name: "text",
		last_name: "text",
		email: "text",
		auth_token: "text",
		role_permissions: {
			type: "frozen",
			typeDef: "<set<role_permission>>"
		},
		last_mod_timestamp: "timestamp",
		create_timestamp: "timestamp",
		status_flag: "int"
	},
	key: ["user_profile_id"]
};
```

Called in app.js like so:

```
try {
	await loadDbConnectionPool();
} catch (e) {
	console.log(e);		
}
```

Results in the following exception being caught:

> apollo.model.tablecreation.schemamismatch: Given Schema does not match existing DB Table "user_profile"migration suspended, please apply the change manually

Strangely enough, this runs properly the first time, without an error. If I restart the app, I get the exception above. If I remove the "role_permissions" collection from the table/entity, the exception does not occur. Single UDTs also work just fine - it's only collections of UDTs that do not.

Reading and writing data through my app appears to work, regardless. It would be nice if migrations could be explicitly disabled, so Cassandra objects (tables, UDTs, etc.) could be managed via scripts and the ORM could simply be used to map to objects.

**Comment by masumsoft** [comment]
Thanks for the detailed report. Latest versions of cassandra has udt collections set to frozen types internally and this raises a mismatch in the udt definition, hence the bug. Going to push fixes handling this special case.

**Comment by shilpavyapari** [comment]
I am still getting this error in 3.0.8 while using Scylla Cloud. Any pointers?

**Comment by masumsoft** [comment]
Scylladb is not [fully supported yet](https://github.com/masumsoft/express-cassandra/issues/137).
