### ISSUE TITLE
Auto timestamp and version fields are not allowed in index and materialized views

### ISSUE THREAD

**Issue by gautamshish09** [masumsoft/express-cassandra#168]
```
const appRoot = require('app-root-path');
const log = require(appRoot + '/config/logger');
const clickEventsModel = require(appRoot + '/models/ClickEventsModel')
const cassandra = require(appRoot + '/config/db/cassandraConnection');
const {
    isLoggedIn
} = require(appRoot + '/common/commonFields');
const modelOptions = require(appRoot + '/common/modelOptions');
const schemaFields = {
    id: {
        type: "uuid"
        , default: {
            "$db_function": "uuid()" //Default to UUID, 
        }
    }
    , userId: {
        type: "text"
        , default: {
            "$db_function": "null" //Defaults to null, 
        }
    }
    , event: "text"
    , isLoggedIn: isLoggedIn
    , visitorId: {
        type: "text"
        , default: {
            "$db_function": "null" //Defaults to null, 
        }
    }
   
};
const clickEventModel = cassandra.loadSchema('clickEvents', {
    fields: schemaFields
    , indexes: ["userId", "event", "visitorId", "createdAt"]
    , key: ["id", "userId", "visitorId"]
    , table_name: "clickevents"
    , options: {
    timestamps: {
        createdAt: 'createdAt' //defaults to createdAt
        updatedAt: 'updatedAt' // defaults to updatedAt
    }
    , versions: {
        key: '__v' // defaults to __v
    }
});
//log.silly("line 25");
//log.silly(cassandra.modelInstance.clickEvents === clickEventModel);
clickEventModel.syncDB(function (err, result) {
    if (err) throw err;
    else
    if (result == true) log.debug("Detected schema changes in clickEvents");
    if (result == false) log.debug("No changes in clickEvents schema");
    // result == true if any database schema was updated
    // result == false if no schema change was detected in your models
});
module.exports = clickEventModel;
```

**Comment by masumsoft** [comment]
@gautamshish09 this is fixed in version 2.2.3

**Comment by gautamshish09** [comment]
Still it's adding 'createdAt' to secondary index. I am getting this error while doing ORDER BY createdAt:

InvalidRequest: Error from server: code=2200 [Invalid query] message="ORDER BY with 2ndary indexes is not supported."

**Comment by gautamshish09** [comment]
Also schema changes done from the models is not being migrated. e.g. If I add a new field, I get an error from express cassandra: "apollo.model.tablecreation.schemamismatch: Given Schema does not match existing DB Table "clickevents""

**Comment by masumsoft** [comment]
@gautamshish09 doesn't your schema suggests it should be added to the secondary index? If you want SASI, you need to define them in `custom_indexes`, right?

regarding migration, if your migration setting is set to "safe" or your NODE_ENV=production, then this is the default behaviour. To turn on automatic migration, you need to set `migration: 'alter'`. More on this in the tutorial: http://express-cassandra.readthedocs.io/en/stable/usage/#explanations-for-the-options-used-to-initialize

**Comment by gautamshish09** [comment]
Even if defined in custom indexes it gives the same error. 
Also the behaviour is same if this field is declared in the primary indexes.

**Comment by masumsoft** [comment]
@gautamshish09 as far as I can understand from your comments, you want to do order by on the createdAt field. As cassandra only allows ORDER BY on clustering columns of your primary key and the partition column must be present in the WHERE clause, so you need your createdAt field to be defined as a clustering key in your primary key definition.

Unless you are using some sort of custom index, by default cassandra does not allow sorting if not defined as a clustering key. This is a limitation imposed by cassandra.

When you say the behaviour is the same, could you refer to which behaviour you are pointing at? Is it the order by issue or the schema mismatch?
