### ISSUE TITLE
Model instance always showing empty ?

### ISSUE THREAD

**Issue by rakibulalam** [masumsoft/express-cassandra#171]
there is no complete documentation to use with express.js.

**Comment by masumsoft** [comment]
express-cassandra is framework independent. There is nothing special you need to do to use it with express.js. You didn't provide any sample code that you tried, so it's difficult to guess what went wrong. But this is a common scenario that if you don't wait for the callback / promise to return, then you won't get the instances loaded.

**Comment by rakibulalam** [comment]
Thank you for your reply. Finally i could able to solve the issue. i think that was my mistake, execute the query before establishing the instance.
