### ISSUE TITLE
apollo.model.find.invalidexpr

### ISSUE THREAD

**Issue by rakibulalam** [masumsoft/express-cassandra#173]
the error message: $expr must be an object containing the index name as string and query as a string

```
var query = {
			$expr: {
				index: 'app_ips_lucene_idx',
				query: { type: 'phrase', field: 'ip', value: '103.94.216.72', slop: 1 }
			}
		};
```
Raw query is working fine 👍 

`SELECT * FROM app_ips WHERE expr(app_ips_lucene_idx, '{ query: {type: "phrase", field: "ip", value: "103.94.216.71", slop: 1}}') LIMIT 1;`

Note 👍I also trying to convert the query object as string format.

**Comment by rakibulalam** [comment]
the solution after traversing your code :
```
var query = {
			$expr: {
				index: 'app_ips_lucene_idx',
				query: JSON.stringify({
					query: {
						type: 'phrase',
						field: 'ip',
						value: '103.94.216.72'
					}
				})
			}
		};
```

**Comment by masumsoft** [comment]
Custom index expression's query must be a string. For your use case I understand it's a bit more work to convert your json object to a string, but custom index queries are not always a json object, hence it can't assume you are providing a json string.

**Comment by rakibulalam** [comment]
Thanks to informing me. As I seen the string error represented that JSON parsable error. This one of the reasons to use it. Another is the formatted helping me to write in the object.
