### ISSUE TITLE
How to set NetworkTopologyStrategy?

### ISSUE THREAD

**Issue by mahfuzak08** [masumsoft/express-cassandra#179]
How to set NetworkTopologyStrategy by using express-cassandra? Please give an example.
Or,
How to use multiple contact point { clientOptions: contactPoints: [ ], ...}...?

**Comment by masumsoft** [comment]
The [documentation](https://express-cassandra.readthedocs.io/en/stable/usage/) provides samples for `SimpleStrategy` and `contactPoints`. I hope that should be fairly simple to extend to use `NetworkTopologyStrategy` and multiple contact points like the following:

```
clientOptions: {
    contactPoints: ['host1.example.com', 'host2.example.com', 'host3.example.com'],
    keyspace: 'your_keyspace',
    queryOptions: { consistency: models.consistencies.quorum }
},
ormOptions: {
    defaultReplicationStrategy: {
      class: 'NetworkTopologyStrategy',
      dc1: 3,
      dc2: 2
    },
    migration: 'safe'
}
```
