### ISSUE TITLE
Schema from Database not validating Type when it has a Reversed type

### ISSUE THREAD

**Issue by hwernstrom** [masumsoft/express-cassandra#18]
from line 388 from base_model.js
db_schema.fields[row.column_name] = TYPE_MAP.find_type_by_dbvalidator(row.validator);
returns null when row.validator = "org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.TimestampType)"

This is cause when the table is created like this.

CREATE TABLE logs (     id1 text,  id2 text,     logdate timestamp,     content text,     user_name text,     PRIMARY KEY (id1, id1, logdate) ) WITH CLUSTERING ORDER BY (id2 ASC, logdate DESC);

My simple fix to this is 

TYPE_MAP.find_type_by_dbvalidator = function(val){
    //decompose composite types
    var decomposed = val ? val.split(/[(,)]/) : [''];

    for (var d in decomposed){
        for(var t in this){
            if (this[t].dbvalidator == decomposed[d])
                return t;
        }
    }
    
    return null;
};

**Comment by masumsoft** [comment]
4433009dc240ab42ab893d03736d0ea6c2bd86c1 fixes the issue and adds support for clustering order in model schema definitions.
