### ISSUE TITLE
unconfigured table schema_keyspaces

### ISSUE THREAD

**Issue by vamzz1** [masumsoft/express-cassandra#20]
I'm using cassandra version 3.0.3. And when im running the node server im getting this error: apollo.model.tablecreation.dbschemaquery: Error while retrieveing Schema of DB Table "ResponseError: unconfigured table schema_keyspaces".
I need some help with this, Is this a compatibility isssue??

**Comment by masumsoft** [comment]
cassandra version 3 is not yet supported

**Comment by vamzz1** [comment]
So what do you suggest, should i downgrade my cassandra to 2.2 or is there any work around for this??

**Comment by masumsoft** [comment]
I would suggest to downgrade to 2.2 for now, supporting version 3 is on the roadmap, but I cannot provide any specific timeline at this moment.

**Comment by vamzz1** [comment]
Sure. Thanks for the help.

**Comment by masumsoft** [comment]
Cassandra 3.x support has arrived along with support for materialized views. The latest v0.6.0 of this module has been tested with cassandra v3.3 so far.
