### ISSUE TITLE
Uncatched huge exceptions in case Cassandra down

### ISSUE THREAD

**Issue by safead** [masumsoft/express-cassandra#214]
During hi load operations when cassandra got down, we got uncatched:

uncaughtException: Error during update query on DB -> NoHostAvailableError: All host(s) tried for query failed. First host tried, 192.168.58.132:9042: BusyConnectionError: All connections to host 192.168.58.132:9042 are busy, 2048 requests are in-flight on a single connection

with a huge additional log paths. All DB operations are in try {} catch{} blocks, but this error immediately terminates the node process without any possibility to catch it. Please assist

**Comment by masumsoft** [comment]
All errors are passed to the callback, hence handling errors in callbacks or promise catch block is expected.
