### ISSUE TITLE
Trying to run save / find query, but throws error "Error during save query on DB -> ResponseError: User meg has no ALTER permission on <keyspace> or any of its parents"

### ISSUE THREAD

**Issue by gopalakrishnanmadhesan** [masumsoft/express-cassandra#248]
Trying to run find query, but throws error 

"Error during save query on DB -> ResponseError: User meg has no ALTER permission on <keyspace> or any of its parents"

**Comment by masumsoft** [comment]
Please check your user permissions on the keyspace. Express cassandra requires full permission on the keyspace to create and alter tables.

https://docs.datastax.com/en/security/5.1/security/secDataPermission.html
