### ISSUE TITLE
settings for multi node cluster

### ISSUE THREAD

**Issue by vamzz1** [masumsoft/express-cassandra#25]
Hey, I just wanted to know what should be contactPoints field in clientOptions be? Should it have ip addresses of all the nodes or only seed nodes ?

**Comment by masumsoft** [comment]
This should be an array of ip addresses or host names of the nodes to add as contact point. It must not have all the nodes and also not require the nodes to be seed nodes. The underlying node driver tries to connect to one of these contact point nodes and get the information about the rest of the cluster. So if at-least one of these contact points are alive, then your app can successfully know the cluster state and load balance against the whole cluster. 

When creating a Cluster instance at client side, the driver tries to connect to the nodes specified in the "contact points" in order. If it fails to connect to the first node, try the next and so on, as long as one node is successfully connected, it does not try to connect the other nodes anymore.

**Comment by vamzz1** [comment]
Thanks a lot for the info.
