### ISSUE TITLE
driver.execute_stream doesn't handle 'error' event.

### ISSUE THREAD

**Issue by mmillies** [masumsoft/express-cassandra#273]
I've been running into a situation where Node.js crashes if this client happens to be reading from a Cassandra node that drops out of a cluster.  The cluster is still online, and the data is available from other replicas, but the fact that this 'error' event isn't handled here, seems to cause Node.js to crash.

execute_stream
https://github.com/masumsoft/express-cassandra/blob/master/src/helpers/driver.js#L99

At first glance it looks relatively straight forward to add a `.on('error', callback)` to the end of this line. In local testing with a single node, adding that handler causes Node.js to no longer crash, and the app started logging the error and moved on.

In the DataStax example usage of `stream` they include handlers for 'end' and 'error'.
https://github.com/datastax/nodejs-driver?tab=readme-ov-file#row-streaming-and-pipes

@masumsoft , Thoughts? I can do a PR if the reasoning holds water with you too.

EDIT:
Naive PR:
https://github.com/masumsoft/express-cassandra/pull/274

**Comment by masumsoft** [comment]
This is released under v2.9.1

**Comment by mmillies** [comment]
> This is released under v2.9.1

yay! super fast. thanks a bunch.
