### ISSUE TITLE
Support for tuple, udt, udf, uda and the frozen keyword

### ISSUE THREAD

**Issue by masumsoft** [masumsoft/express-cassandra#28]
Currently there is no support for tupple types, user defined types and user defined functions. It would be great if the module supported these types.

**Comment by asplogic** [comment]
Do you have any time frames when v1.0.0 will be released?  The project seems promising but will be great once these functionalities are added.

**Comment by masumsoft** [comment]
I cannot provide any specific date at this moment, but stay tuned, hopefully the 1.0 will be released soon.

**Comment by masumsoft** [comment]
Reference docs: 

https://docs.datastax.com/en/cql/3.3/cql/cql_reference/tupleType.html
https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlRefUDType.html
https://docs.datastax.com/en/cql/3.3/cql/cql_using/useCreateUDF.html

**Comment by asplogic** [comment]
Do you have any ideas on how these will be implemented such as how they get defined, etc.

**Comment by masumsoft** [comment]
@asplogic 

the tuple definition would be similar to the collection data types, something like the following:

```
currencies: {
    type: 'tuple',
    typeDef: '<text, int, text>'
}
```

The udt and udfs would be defined globally against your keyspace, probably in the configuration object passed to initialize express-cassandra, so that express cassandra could create them if not exist and you may be able to use them in your schema definition and queries. So your configuration object might have two more keys along with the clientOptions and ormOptions something like the following:

```
    {
        clientOptions: {
            ...
        },
        ormOptions: {
            ...
        },
        udts: {
            address: {
                city: '',
                street: '',
                ...
            },
            ...
        },
        udfs: {
            fLog: {
                language: 'java',
                code: 'return Double.valueOf(Math.log(input.doubleValue()));',
                returnType: 'double',
                inputs: ['input double']
            }
        }
    }
```

**Comment by asplogic** [comment]
Cheers!  Can't wait to try it out!

**Comment by masumsoft** [comment]
Thanks, though 1.0 is not released yet, it's very close to be there. I'm working on improving the automatic migrations support at this moment and hopefully will be completed soon.

**Comment by masumsoft** [comment]
@asplogic Version 1.0 has been released!

**Comment by asplogic** [comment]
Thanks for the update!  I'll give a shot soon.

**Comment by Bamieh** [comment]
@masumsoft what do you think of having a `models/*Type.js` to auto detect UDT? same goes for the other User defined things. If you think it is reasonable, i will open an issue and try to fiddle around with the code
