### ISSUE TITLE
Streaming in cassandra

### ISSUE THREAD

**Issue by vamzz1** [masumsoft/express-cassandra#29]
Hey, I was just wondering how we would go about in doing a streaming query similar to the one in mongo.

**Comment by masumsoft** [comment]
You may want to look at this: http://docs.datastax.com/en/developer/nodejs-driver/3.0/nodejs-driver/reference/paging.html

To implement this with the orm, right now the only way is to get the client driver instance like the following: 

```js
models.instance.Person.get_cql_client(function(err, client){
    client.eachRow('Select * from person limit 10', [], { autoPage : true }, function(n, row) {}, function(err, result){});
});
```

Supporting streaming query from the orm is also a nice to have feature to be backed into the orm. I hope these features will also be part of the orm soon. I'll be working on the 1.0 version of this orm where these features are planned to be present by then.

**Comment by vamzz1** [comment]
Thanks a lot. Really helpful info. Looking forward for orm level support.
