### ISSUE TITLE
Complex Order by query giving errors

### ISSUE THREAD

**Issue by vamzz1** [masumsoft/express-cassandra#30]
Hey, when i am trying complex order by during find query $orderby:{'$desc' : ['k1','k2']. it's giving this error : Error fetching events: apollo.model.find.dberror: Error during find query on DB -> ResponseError: Unsupported order by relation. I am specifying k1  and k2 in the same order they are in my keyspace and also i checked that there are no spelling mistakes. So is there anything i am missing here??

**Comment by masumsoft** [comment]
Could you please post your model definition, so I can see the whole picture?

**Comment by vamzz1** [comment]
[image: Inline image 1]   profileId is the partition key which is text,
dummyForProfileId is a clustering key which is text, receivedAt is another
clustering key which is time stamp. The query looks like this
 var query = {
    profileId: someVal,
    dummyForProfileId: someVal,
    receivedAt: {'$gt': lastWeek},
    $orderBy: {'$desc': ['dummyForProfileId', 'receivedAt']}
    $limit: 100
  };

**Comment by masumsoft** [comment]
If you mention the `dummyForProfileId` in the query, then the `dummyForProfileId` in orderBy does not make sense. You should remove it from either the orderby or the query clause.

**Comment by vamzz1** [comment]
But then i would not be able to use recievedAt >=lastWeek without
specifying allow filtering right??,  because the clustering keys have to be
ordered.

**Comment by masumsoft** [comment]
Okay, could you please share with me what do you want to achieve with this query? So I could understand your requirements better and could suggest you the cassandra way of doing it.

**Comment by vamzz1** [comment]
Basically what i want to achieve is to get the latest 'n' events of a
profile, so profileId is the partition key and because i wanted all the
events of a profile to be stored to together, i created another field
dummyForProfileId which stores the profileId itself as the clustering key
and then also because i wanted the events to be sorted in decreasing order
of the time they are received i made receivedAt as the second clustering
key. By the way as i am retrieving only a few documents i can always sort
them after i receive them based on time, but i just wanted to know if we
could do it inherently.

**Comment by masumsoft** [comment]
Ok, then it was not necessary to create the `dummyForProfileId ` field. Your data is stored by cassandra according to your primary key definition. By the partition key, cassandra decides in which partition to keep your data and by the clustering keys it decides how it would keep the data sorted under that partition. So to get the latest 'n' events, your primary key definition should have the `profileId` as the partition key and the `receivedAt` as the clustering key. By doing this, cassandra will keep your data partitioned by `profileId` and in each partition sorted by `receivedAt`. 

So when you query by profileId, cassandra can find the correct partition and then read the data in the that partition that is already sorted in ascending order by default. If you want desc order, you may tell cassandra to sort it in desc order using the `clustering_order` in schema definition or you can use the orderby query.

So you can easily get the latest say '100' events by simply removing the unnecessary dummyForProfileId from the schema and using a query like the following:

```js
var query = {
    profileId: someVal,
    $orderBy: {'$desc': 'receivedAt'}
    $limit: 100
};
```

In addition to this, if you want those latest events to be within last week:

```js
var query = {
    profileId: someVal,
    receivedAt: {'$gt': lastWeek},
    $orderBy: {'$desc': 'receivedAt'}
    $limit: 100
};
```

**Comment by masumsoft** [comment]
To clarify my answer more, cassandra will keep a partition (row) for each unique value of the partition key field. So for each unique profileId, there will be a partition in which cassandra will keep all the events of that profileId. Now if you tell cassandra to cluster that partition according to the receivedAt field, then it will simply keep the events for that profileId in that profileId partition sorted for ordered retrieval.

**Comment by vamzz1** [comment]
Oh thanks man. This was super helpful man. I thought we had to manually add
a clustering key so that all the events of a profile are stored together,
if cassandra is already doing then it's really good for our use case.
