### ISSUE TITLE
Doesn't connect to database

### ISSUE THREAD

**Issue by marcelolucio1982** [masumsoft/express-cassandra#31]
Hello, I am unable to connect to my database. The models are not being charged.
The code snippet does not run:

`async.each(list, function(file, callback) {

                    var fileName = self.directory + '/' + file;
                    if(fileName.indexOf('Model') == -1) {
                        callback();
                        return;
                    }

                    var modelName = self._translateFileNameToModelName(file);

                    if(modelName) {
                        var modelSchema = require(fileName);
                        self.modelInstance[modelName] = self.orm.add_model(
                            modelName.toLowerCase(),
                            modelSchema,
                            function(err, result){
                                if(err) {
                                    callback(err);
                                }
                                else callback();
                            }
                        );
                    }
                    else {
                        callback();
                    }

                }`

Follow my snippet code:

`var models = require('express-cassandra');

var options = {
    clientOptions: {
        contactPoints: ['localhost'],
        protocolOptions: { port: 9042 },
        keyspace: 'chatplace',
        queryOptions: {consistency: models.consistencies.one}
    },
    ormOptions: {
        defaultReplicationStrategy : {
            class: 'SimpleStrategy',
            replication_factor: 1
        },
        dropTableOnSchemaChange: false,
        createKeyspace: true
    }
}

models.setDirectory( pathRootApp + '/models').bind(options);`

**Comment by masumsoft** [comment]
Exactly what did you mean by "The code snippet does not run"? It looks like you've taken the code segment from the module itself instead of using it's documentation. Did you try the [Usage](https://github.com/masumsoft/express-cassandra#usage) section on how to use this module? Could you please share the code snippet that you used to connect to cassandra?

**Comment by masumsoft** [comment]
Please note that your model file names must have the word `Model` in it, i.e. PersonModel.js

**Comment by marcelolucio1982** [comment]
Follow my snippet code:

```
var models = require('express-cassandra');

var options = {
clientOptions: {
contactPoints: ['localhost'],
protocolOptions: { port: 9042 },
keyspace: 'chatplace',
queryOptions: {consistency: models.consistencies.one}
},
ormOptions: {
defaultReplicationStrategy : {
class: 'SimpleStrategy',
replication_factor: 1
},
dropTableOnSchemaChange: false,
createKeyspace: true
}
}

models.setDirectory( pathRootApp + '/models').bind(options);
```

my mode UsuarioModel.js:

```
module.exports = {
   "fields":{
        "id_usuario":  { "type": "uuid"},
        "senha": { "type": "varchar"  }
        "nome": { "type": "varchar"},
        "email":    { "type": "varchar"},
        "telefone": { "type": "varchar"},
        "data_hora_cadastro" : { "type": "timestamp"},
        "latitude" : {"type": "bigint"},
        "longitude" :{"type": "bigint"}
    },
    "key":["id_usuario"]
}
```

**Comment by marcelolucio1982** [comment]
When the snippet run throw exception.

code:
`var users = new models.instance.Usuario({nome : 'XXXX', senha: 'XXXX', email : 'XXXX@XXX.XX'});`

exception:

```
var users = new models.instance.Usuario({nome : 'XXXX', senha: 'XXXX', email : 'XXXX@XXX.XX'});
               ^

TypeError: models.instance.Usuario is not a function
    at Object.<anonymous> (D:\Projeto\workspace-node\chat-place-server\servidor.js:21:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.runMain [as _onTimeout] (module.js:467:10)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by masumsoft** [comment]
The bind function takes a callback as the second argument if you look at the example in the documentation. This is asynchronous, so you need to use your models after the callback fires successfully. Try something like this:

```js
models.setDirectory( pathRootApp + '/models').bind(options, function(err){
    var users = new models.instance.Usuario({nome : 'XXXX', senha: 'XXXX', email : 'XXXX@XXX.XX'});
});
```

**Comment by marcelolucio1982** [comment]
Thank you for response, but the error persists

**Comment by masumsoft** [comment]
What's the output of `console.log(pathRootApp);` ?

**Comment by marcelolucio1982** [comment]
The root of the project. Can I send the project for you? It has only two files, the model and the connection

**Comment by masumsoft** [comment]
Yeah, if you could send me the project, it would help me to figure out whats happening.

**Comment by marcelolucio1982** [comment]
Send to your email

**Comment by marcelolucio1982** [comment]
Send to your email

**Comment by marcelolucio1982** [comment]
Rename app.txt to app.js and UsuarioModel.txt to UsuarioModel.js

On Tue, Apr 5, 2016 at 6:04 PM, Marcelo <marcelo.lucio1982@gmail.com> wrote:

>
>
> On Tue, Apr 5, 2016 at 5:24 PM, Masum <notifications@github.com> wrote:
>
>> Yeah, if you could send me the project, it would help me to figure out
>> whats happening.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/masumsoft/express-cassandra/issues/31#issuecomment-205974623>
>>
>
>
>
> --
> Atenciosamente,
> *Marcelo Lúcio O. Nogueira*
> Cel.: 8220-0798
> Skype: marcelolucio1982
> LinkedIn: https://www.linkedin.com/pub/marcelo-onofre/24/104/197
>



-- 
Atenciosamente,
*Marcelo Lúcio O. Nogueira*
Cel.: 8220-0798
Skype: marcelolucio1982
LinkedIn: https://www.linkedin.com/pub/marcelo-onofre/24/104/197

**Comment by masumsoft** [comment]
ok got it working after making two changes in your code. First one is your model definition object was missing a comma after the `senha` field definition. Secondly, what i told you before, you need to use the models after the callback fires. Though you've done that, but was still getting errors because your previous usage outside the calback function was still there which was the reason behind the errors. The two files now look like the following:

UsuarioModel.js

```js
module.exports = {
   "fields":{
        "id_usuario":  { "type": "uuid"},
        "senha": { "type": "varchar"  },
        "nome": { "type": "varchar"},
        "email":    { "type": "varchar"},
        "telefone": { "type": "varchar"},
        "data_hora_cadastro" : { "type": "timestamp"},
        "latitude" : {"type": "bigint"},
        "longitude" :{"type": "bigint"}
    },
    "key":["id_usuario"]
}
```

app.js

```js
var app = require('express')();
var http = require('http').Server(app);
var models = require('express-cassandra');

var path = require('path');
global.pathRootApp = path.resolve(__dirname);

app.get('/', function(req, res){
  res.send('<h1>Running!!!</h1>');
});

http.listen(3000, function(){
  console.log('listening on *:3000');
});

var options = {
    clientOptions: {
        contactPoints: ['localhost'],
        protocolOptions: { port: 9042 },
        keyspace: 'chatplace',
        queryOptions: {consistency: models.consistencies.one}
    },
    ormOptions: {
        defaultReplicationStrategy : {
            class: 'SimpleStrategy',
            replication_factor: 1
        },
        dropTableOnSchemaChange: false,
        createKeyspace: true
    }
    
}

models.setDirectory( pathRootApp + '/models').bind(options, function(err) {
    if(err) {
        return console.log(err);
    }
    
    var usuario = new models.instance.Usuario({id_usuario: models.uuid(), nome : 'XXXX', senha: 'XXXX', email : 'XXXX@XXX.XX'});
    usuario.save(function (error){
        if(error) {
            console.log('Error during user save: ' + error);
          } else {
            console.log('User saved ');
          }
    });
});

```

**Comment by marcelolucio1982** [comment]
Its work masumsoft. Thank you very mutch!!!
