### ISSUE TITLE
Specify SELECT * for materialized view columns

### ISSUE THREAD

**Issue by AntiEntropy** [masumsoft/express-cassandra#33]
Hi,

When creating a materialized view using CQL it is possible to specify SELECT * FROM <table_name> for the columns to use instead of specifying each column. Can you add a similar feature to express-cassandra? e.g. allow specifying `select: ["*"]`  or `select: "*"`

Thanks!

**Comment by masumsoft** [comment]
`select: ["*"]` is now supported in v0.8.1
