### ISSUE TITLE
Updating list using update command

### ISSUE THREAD

**Issue by vamzz1** [masumsoft/express-cassandra#35]
Hey, I wanted to know if we can update a list, i.e, add an element at the end of the list by using update command in the orm which i verified can be done from the cqlsh shell using the update command. We can obviously do it by finding the row, adding the changes we want and saving back the row, just wondering if we can achieve this using the update command.

**Comment by masumsoft** [comment]
This feature is added in the latest version 0.8.0 published into npm (commit bd042d3cafbe8c8df9891233765beb7bd69707b9)

Documentation of how to do it is available here: https://github.com/masumsoft/express-cassandra#support-for-composite-data-types
