### ISSUE TITLE
Support for static columns

### ISSUE THREAD

**Issue by AntiEntropy** [masumsoft/express-cassandra#36]
Are static columns supported? If not could you add support for specifying a list of static columns on a table?

**Comment by masumsoft** [comment]
Yes coming up in 1.0, hopefully soon.

**Comment by AntiEntropy** [comment]
Awesome, thank you!

**Comment by masumsoft** [comment]
Reference docs: https://docs.datastax.com/en/cql/3.3/cql/cql_reference/refStaticCol.html
