### ISSUE TITLE
Support for indexing with SASI

### ISSUE THREAD

**Issue by masumsoft** [masumsoft/express-cassandra#43]
Reference docs: 
https://docs.datastax.com/en/cql/3.3/cql/cql_using/useSASIIndexConcept.html
https://docs.datastax.com/en/cql/3.3/cql/cql_using/useSASIIndex.html
https://docs.datastax.com/en/cql/3.3/cql/cql_reference/refCreateSASIIndex.html

**Comment by masumsoft** [comment]
Right now SASI indexes can be created using the `custom_index` attribute in schema definitions which is a work around at this moment. The problem is only a single custom index is supported at this moment because previous versions of cassandra supported only a single custom index per table. So until this issue is fixed to allow multiple custom indexes, only a single SASI index can be created.

**Comment by thelordoftheboards** [comment]
Is it possible to add the indexes through additional CQL?

**Comment by masumsoft** [comment]
The latest v1.1.0 contains support for indexing with SASI and multiple custom indexes. You can provide an array of custom indexes in the new `custom_indexes` attribute. The old custom_index attribute will continue to work as expected, but does not support multiple custom index definition. For multiple custom indexes, use the `custom_indexes` field.

**Comment by masumsoft** [comment]
@thelordoftheboards I hope the latest support for multiple sasi indexes in v1.1.1 helps, other important issues like migrations and crud hooks are on their way. I hope to work on them soon.

**Comment by thelordoftheboards** [comment]
@masumsoft thank you very much. I was reading the issue list and I was left with the impression that having multiple SASI indexes was not an option. Happy to hear it is possible!

**Comment by thelordoftheboards** [comment]
As for the migrations, what is the general approach you are planning to take? Will express-cassandra generate ALTER TABLE statements?

**Comment by masumsoft** [comment]
The probable approach is documented here: https://github.com/masumsoft/express-cassandra/issues/27#issuecomment-235051628

**Comment by thelordoftheboards** [comment]
@masumsoft thank you very much for your detailed responses, and for creating and sharing this module in the first place.

I am looking forward to incorporating it into the boilerplate for Cassandra I am working on. I appreciate the attention to detail and the breadth of supported features, including the collection data types. I did not see support for those in the order ORMs available on npm.
