### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by abrookbanks** [masumsoft/express-cassandra#49]
delete

**Comment by masumsoft** [comment]
The documentation has been updated to contain an example to use authProvider, also for convenience the v1.0.1 contains a `models.driver` access point to access the nodejs driver for auth related functions.

**Comment by abrookbanks** [comment]
Thanks so much. I edited the title back which I removed as I thought I was being stupid. It may then help others.

Keep up the great work.

**Comment by chrisabrams** [comment]
On the [readme page](http://express-cassandra.readthedocs.io/en/latest/usage/) under "Alternatively Load & Organize Models Yourself" it says:

```
var Cassandra = require('express-cassandra');
var models = Cassandra.createClient({
    clientOptions: {
        contactPoints: ['127.0.0.1'],
        protocolOptions: { port: 9042 },
        keyspace: 'mykeyspace',
        queryOptions: {consistency: Cassandra.consistencies.one}
    },
    ormOptions: {
        defaultReplicationStrategy : {
            class: 'SimpleStrategy',
            replication_factor: 1
        },
        migration: 'safe',
        createKeyspace: true
    }
});

models.connect(function (err) {
    if (err) throw err;

    var MyModel = models.loadSchema('Person', {
        fields:{
            name    : "text",
            surname : "text",
            age     : "int"
        },
        key:["name"]
    }, function(err, UserModel){
        //the table in cassandra is now created
        //the models.instance.Person, UserModel or MyModel can now be used
        console.log(models.instance.Person);
        console.log(models.instance.Person === UserModel);
        console.log(models.instance.Person === MyModel);
    });
});
```

The next section says that in order to authenticate you need to add the driver:

    authProvider: new models.driver.auth.PlainTextAuthProvider('my_user', 'my_password')

However, `models` is not defined in this scenario. How do you add the auth driver if you manually define & load the models?

**Comment by masumsoft** [comment]
Thanks for reporting. The doc needs to be updated as in recent versions of express-cassandra, the cassandra-driver has been replaced with dse-driver to allow enterprise functionalities. So the authenticator you need to use is DsePlainTextAuthProvider. So using something like the following should work:

```
new Cassandra.driver.auth.DsePlainTextAuthProvider('user', 'pass')
```

**Comment by chrisabrams** [comment]
@masumsoft 👍
