### ISSUE TITLE
TTL for materialized views

### ISSUE THREAD

**Issue by vamzz1** [masumsoft/express-cassandra#50]
Hi, i was wondering if we could set a default_time_to_live for a materialized view similar to the one we set while creating a table. I tried it myself in cqlsh with no luck but i could not find any document saying we couldn't do it.

**Comment by masumsoft** [comment]
As per cassandra docs, you can set the table properties for your materialized views: https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlRefAlterMV.html

Express cassandra does not directly support setting table properties, there is an issue (#45) around supporting this. I hope to work on this in the near future, but for now, you can use cqlsh to set the properties you want.
