### ISSUE TITLE
Any plans to use promise library?

### ISSUE THREAD

**Issue by asplogic** [masumsoft/express-cassandra#52]
Are there any plans to use a promise library such as bluebird?  Thanks

**Comment by masumsoft** [comment]
Supporting promises is not yet a planned feature, but I'll consider supporting it at a later time. PRs are welcome too.

**Comment by ssuperczynski** [comment]
Hey, me and @Gustu will add promises to this library

**Comment by masumsoft** [comment]
@ssuperczynski great! let's move on!

**Comment by Multiply** [comment]
@ssuperczynski any progress on this?

**Comment by ssuperczynski** [comment]
Sorry, we stopped developing our app, so we didn't manage to finish it.

**Comment by zckrs** [comment]
Hi,
To use Promise maybe we can use https://github.com/sindresorhus/pify

😬

**Comment by Sadia-Alauddin** [comment]
Is there any progress on this thread?

**Comment by masumsoft** [comment]
Okay, I'm going to implement the promise support within short time

**Comment by masumsoft** [comment]
v1.6.0 now supports promises out of the box. Refer to the doc here: https://github.com/masumsoft/express-cassandra/blob/master/docs/usage.md#built-in-promise-support
