### ISSUE TITLE
Table is not being created when column type is counter

### ISSUE THREAD

**Issue by ssuperczynski** [masumsoft/express-cassandra#58]
Given I have schema:

```js
const ShareLikeCounterByUser = {
  fields: {
    id: {
      type: "uuid",
      default: {"$db_function": "uuid()"}
    },
    name: "varchar",
    photo: "varchar",
    like: "counter",
    share: "counter",
    facebook_id: "varchar",
    work: "varchar",
    created: {
      type: "date",
      default: {"$db_function": "toTimestamp(now())"}
    }
  },
  key: ["facebook_id", "created"],
  indexes: ["facebook_id", "created"],
  table_name: "share_like_counter_by_user"
};

export default ShareLikeCounterByUser;
```

table is not created in C* but library does not return any errors. 
<img width="147" alt="screen shot 2016-07-08 at 10 17 20" src="https://cloud.githubusercontent.com/assets/6843074/16681489/5d234cca-44f5-11e6-8036-8c06e4307063.png">

But when I comment counters
```js
   // like: "counter",
   // share: "counter",
```

table is beaing created in C*
<img width="209" alt="screen shot 2016-07-08 at 10 17 43" src="https://cloud.githubusercontent.com/assets/6843074/16681486/58a5a5f8-44f5-11e6-9fc1-7f7fcb3e61d5.png">

Am I doing something wrong?

**Comment by masumsoft** [comment]
Cassandra only supports counter columns when your non counter columns are part of the primary key definition. Cassandra does not support this for variety of reasons, implementing distributed counters is hard and these restrictions apply wherever you want to use them. Counter limitations are documented in cassandra docs and is listed in the readme of this module. You may want to read more [here](https://docs.datastax.com/en/cql/3.3/cql/cql_using/useCountersConcept.html).

**Comment by ssuperczynski** [comment]
Wow, didn't know that. Thanks for the url
