### ISSUE TITLE
Get response on save

### ISSUE THREAD

**Issue by amanpurohit** [masumsoft/express-cassandra#59]
Is there a way to get back the object saved using `.save()` function. I am getting info, columns and pageState in the response object right now.

Sample Query

`user.save(function(err, user) {if(!err) res.json(user)})`

Express Cassandra Version: 1.0.3
Cassandra: 3.0.7

**Comment by masumsoft** [comment]
You cannot directly get the object saved from the `save()` function callback. You need to do a `find` after you've saved it. Btw, if you want to just show the user object from the user instance, you could possibly do `user.toJSON()` to get the raw values inside the user object.

**Comment by amanpurohit** [comment]
Okay thanks . Actually I wanted to return the id of the newly created user. Anyways I will run the find query for it.

**Comment by kenzdozz** [comment]
If the ID is auto-generated and is the only unique field, running a find query may get the wrong data
