### ISSUE TITLE
Not really an issue...but

### ISSUE THREAD

**Issue by pandafinity** [masumsoft/express-cassandra#6]
Hello,

Not really an issue, but wondered how I would create a composite key (like a one to many relationship).

I want to try and map Artists and Albums - so with an album have the key made up of the artist id and the album id.  Would you be able to explain this in your examples?

Really appreciate any help you can provide.

Enjoy your weekend :)

**Comment by masumsoft** [comment]
@pandafinity In cassandra, data modeling depends on the queries you need to serve. So what are your expected queries?

**Comment by pandafinity** [comment]
Well, I am simply looking to see how I would set a composite key in the nameModel.js.

Your example talks about a partition key and a cluster key , so I am wondering how I show a composite key using your definitions.  E.g. A key made up of 'artist id' & 'album id' - your example doesn't talk about composite keys.

I also wanted to ask about closing a connection to Cassandra.  I ask as I am using your module in an Async Waterfall - but it is your module that prevents the Async Waterfall from passing through and terminating (naturally) the Node.js code.  - which I can only assume is due to the connection staying open.  I have debugged the code and it comes back to the model.setDirectory command - so wondered if this is meant to be closed (and How) or if this should not be used in an Async environment?

Thanks for your help in advance.

**Comment by masumsoft** [comment]
Well in that case the example already demonstrates that you can provide an array for the partition key, which means you can make a composite partition key like the following:

```
module.exports = {
    fields:{
        artist_id: "int",
        album_id: "int"
    },
    key : [["artist_id","album_id"]],
}
```

I'll clarify this in the doc that the partition key array is meant to be for composite partition keys. 

Regarding the connection closing issue, the latest version of express-cassandra module has a `models.close(callback)` function. You may want to use this. 

Thanks.

**Comment by masumsoft** [comment]
Closing this issue as it looks like the problem has been resolved
