### ISSUE TITLE
Call virtuals when update or insert data without explicit call

### ISSUE THREAD

**Issue by CordlessWool** [masumsoft/express-cassandra#63]
I do not know if it is a bug or should be a function. When I use virtuals first time I think they will call by calling update or creating new instance of model. But they have to call explicit, so i can not use them with update. Are there are any plans to call them automaticly if some variable with same name is set? Could it be implement?

**Comment by masumsoft** [comment]
Could you provide an example to elaborate on the problem you are facing and describe your expected output?

**Comment by CordlessWool** [comment]
I have a virtual in my model like:
_status: {
            type: 'varchar',
            virtual: {
...
but if I set the variable data._status
and create a new instance of model new model.instance.Table(data);
get and set functions of _status i definied are not called. Same by updating

**Comment by masumsoft** [comment]
@CordlessWool You need to create the model instance first and then set the `_status` property on the returned model instance to make sure the virtual field setter function triggers properly. Before creating the model instance, data is just a plain javascript object. Do it like the following:

```js
data = new model.instance.Table(data);
data._status = ... ; // this will trigger your virtual field set function.
var status = data._status ; // this will trigger your virtual field get function
```

Hope this helps. Thanks.

**Comment by CordlessWool** [comment]
Ok, i miss understood the function at first time. 
And it would not possible to implement the way I think it should work.
Thank you for describing
