### ISSUE TITLE
A `rule` model field property doesn't work properly.

### ISSUE THREAD

**Issue by aleksandrsorokin** [masumsoft/express-cassandra#66]
A validator doesn't execute if field value is `undefined`. There is a way to define model property as `required` and throw error if it's value is `undefined`?

**Comment by aleksandrsorokin** [comment]
And it's looks like 
```js
name: {
  type: 'varchar',
  default: function() { return 'default'; },
},
```
doesn't work too.

**Comment by aleksandrsorokin** [comment]
@masumsoft thank you alot

**Comment by masumsoft** [comment]
@aleksandrsorokin the latest version 1.3.0 contains the fixes. For doc updates regarding this fix, have a look at the following: 

https://github.com/masumsoft/express-cassandra/blob/v1.3.0/docs/validators.md
