### ISSUE TITLE
Bug: Do not call materialzied Views if using paging

### ISSUE THREAD

**Issue by CordlessWool** [masumsoft/express-cassandra#67]
I tried to use eachRow with a materialized view but get only error back. It says that i have to set value for id, but id is only in the orginal table part of the clustering key. What I want to request was:

Select * from kitas_by_city where city = 'Berlin' and status in ('outlawed', 'published') and district = 'Moabit'

kitas_by_city are one materilized view
I tested it with eachRow of cassandra-driver, it works without an issue. I think the issue in your code is, that option materialized_view is ignored when calling eachRow. 

Could you fix it? How long would it take? Could I help?

You build a very great tool, thanks.

**Comment by masumsoft** [comment]
Yes, you are right, this is a bug. eachRow method implementation ignores the options object, I'm having a look at it and hopefully will fix it within short time.

**Comment by masumsoft** [comment]
@CordlessWool this is now fixed in the latest version 1.3.1, hope this helps

**Comment by CordlessWool** [comment]
Thank you

**Comment by CordlessWool** [comment]
Works fine, thank you
