### ISSUE TITLE
when specifiying udts, getting schemamismatch

### ISSUE THREAD

**Issue by AlmaasAre** [masumsoft/express-cassandra#68]
Seems like when i specify a udts, no matter if the schema is unchanged, it seems to want to drop the schemas anyway. Anyone else experiencing this?

![image](https://cloud.githubusercontent.com/assets/1777366/18206402/d3b37088-7126-11e6-8e9c-a53e7884f51c.png)

It's when i use the UDT in any of my Models. 

- official docker image with cassandra 3.7 
- express-cassandra 1.0.2. Tried using version 1.3.* too, but got tty errors because it tried to interact through the shell.

**Comment by AlmaasAre** [comment]
Figured it out:

![image](https://cloud.githubusercontent.com/assets/1777366/18206582/a477644a-7127-11e6-97fd-b5af8bbb22b0.png)


Seems like when defining a UDT in the model, you can't specify the udt as camel-case....

**Comment by masumsoft** [comment]
The latest version 1.3.3 contains fixes for it. Also as cassandra treats field or type names as lowercased by default unless you explicitly use double quotes surrounding the name, so your schema implementation should look like the following:

```js
parts: {
  type: 'set',
  typeDef: 'frozen<"messagePart">'
}
```

notice the double quotes surrounding your type name. 

Now regarding the tty errors, could you please tell me the os and node versions you were using? When there are any data destructive migrations needed due to schema change, the module will ask the user for confirmation in the  terminal. So what kind of tty errors you are getting. Are you using docker for your node app too?

**Comment by AlmaasAre** [comment]
Nice.
> the module will ask the user for confirmation in the terminal.

That's exactly it. I use nodejs:6.2-slim for the app, and cassandra:3.7. It's all docker. I guess that nodejs:6.2-slim doesn't have interactive mode on, so when it tries to prompt the user, it fails hard. 

Why does it prompt the user about each table. Not possible/easier to just use a env-variable instead? Or have a way of disabling user interaction, because if not, I can't use the slim image anymore + if i publish the app to a cloud-service, and I want to alter a table if it has changed, I won't have control of the user-interaction.

**Comment by masumsoft** [comment]
The terminal confirmation is there to protect accidental deletion of data. Automatic migration is not a safe operation to do in production. It's recommended to use the `migration: 'safe'` option and do the migrations yourself while in production. The convenience of having automatic migration is not generally worth the trouble of accidentally losing your production data. 

For example, if your primary key definition changes, cassandra has no way to alter that table. So the migration system would have to drop and recreate the table and all the data in it will be lost. Doing such an operation without the user confirmation might be devastating as we all are humans and we do mistakes. 

But yes you are right, there should be an option to disable the user interaction and option to go ahead understanding the consequences. Environments without tty support is a perfect example use case. I'll be working on it soon to allow disabling user interactions.

**Comment by AlmaasAre** [comment]
> The terminal confirmation is there to protect accidental deletion of data. Automatic migration is not a safe operation to do in production. It's recommended to use the migration: 'safe' option and do the migrations yourself while in production. The convenience of having automatic migration is not generally worth the trouble of accidentally losing your production data.

I definitely see that. But when iterating fast on a MVP, we want to able to alter the tables in the development-environment automatically to create a frictionless workflow

> But yes you are right, there should be an option to disable the user interaction and option to go ahead understanding the consequences. Environments without tty support is a perfect example use case. I'll be working on it soon to allow disabling user interactions.

Awesome! 👍

**Comment by masumsoft** [comment]
@AlmaasAre the latest version 1.4.0 contains features like hook functions for save/update/delete operations and along with them, supports the requirement of this issue, which is allowing to disable tty confirmation. Quoting from the latest doc:

> Note that some environments might not support tty console, so asking the user for confirmation in the terminal may throw errors. If you face such problems or want to automate the migration process in a dev/staging environment then you can set the property `disableTTYConfirmation: true` in the `ormOptions`. This will do the migrations without asking for a confirmation from the user.

**Comment by AlmaasAre** [comment]
Sweet, thank you @masumsoft!
