### ISSUE TITLE
Invalid String Representation of Uuid

### ISSUE THREAD

**Issue by amanpurohit** [masumsoft/express-cassandra#69]
I am getting this error while passing an invalid string to `Cassandra.uuidFromString()` function. It crashes my express app. How can I handle this error gracefully. Attaching a screenshot for your reference.

![workspace 1_001](https://cloud.githubusercontent.com/assets/5153029/18675697/d3f00554-7f70-11e6-9dfd-fcbb54addf83.png)

**Comment by masumsoft** [comment]
You can use standard try catch block to catch a thrown error like the following:

```
var uuid;
try {
    uuid = Cassandra.uuidFromString(str);
} catch (err) {
    console.log(err);
}
```

**Comment by amanpurohit** [comment]
Okay. Thanks !! :+1:
