### ISSUE TITLE
Null error in apollo_schemer.js

### ISSUE THREAD

**Issue by VipulSarin** [masumsoft/express-cassandra#7]
While setting a cassandra timeuuid field, I get a null object error in apollo_schemer.js
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Cannot read property 'virtual' of null
 at Object.schemer.normalize_model_schema (/express-cassandra/lib/orm/apollo_schemer.js:43:43)

My Model is: 
module.exports = {
    fields: {
        "email" : {"type": "text"},
        "id"     : { "type": "timeuuid"},
        "body" : {"type": "text"}
    },
    "key" : [["email"],"id"]
};

Upon investigating I realized that the output schema from lodash.clone in apollo_schemer.js was changing the id value to null. I was able to create a workaround fix by catching the null value and changing it back to timeuuid.

**Comment by masumsoft** [comment]
Could you elaborate a bit on how did you generate the timeuuid before setting the field? Are you using the `models.timeuuid()` function to generate the timeuuid?

**Comment by VipulSarin** [comment]
I was using node-uuid to generate the actual timeuuid. I just tried it again with models.timeuuid(), but I still go the same error. I think the problem is with the schema rather than what method I use to generate it when I'm inserting data.

**Comment by masumsoft** [comment]
@VipulSarin I've written a test case to validate this, but my test cases are working nicely. Your error message suggests that may be your version is a bit older. Are you using the latest version (v0.4.9) of express-cassandra?

**Comment by VipulSarin** [comment]
I am using the latest version. I just checked using npm list. Hmm.. maybe I am doing something wrong, if your test cases are passing. Is there any other information that I could give you which might help in resolving this? For example, this is the (admittedly, crude) fix that I've put in apollo-schemer.js to fix the issue for now (line 32) : 
```javascript
for(k in output_schema.fields){
            if (typeof (output_schema.fields[k]) == 'string' )
                output_schema.fields[k] = {'type':output_schema.fields[k]};
            else {
                //console.log(output_schema.fields[k])
                **if(output_schema.fields[k] == null){
                    output_schema.fields[k] = {"type":"timeuuid"}
                }**
                else if(output_schema.fields[k].virtual){
                    delete output_schema.fields[k];
                }else{
                    output_schema.fields[k] = {'type':output_schema.fields[k].type};
                }
            }

            if(output_schema.fields[k] && output_schema.fields[k].type == 'varchar') {
                output_schema.fields[k].type = 'text';
            }
        }
```

**Comment by masumsoft** [comment]
Could you please send the code snippet where you are setting the timeuuid value? Following is my working version:

```
//EventModel.js file
module.exports = {
fields: {
"email" : {"type": "text"},
"id" : { "type": "timeuuid"},
"body" : {"type": "text"}
},
"key" : [["email"],"id"]
};
```

```
//Saving object with timeuuid value
var event = new models.instance.Event({
    email: 'a@b.com',
    id: models.timeuuid(),
    body: 'hello world'
});
event.save(function(err){
    if(err) throw err;
    console.log("Yuppy");
});
```

**Comment by VipulSarin** [comment]
Sure, here you go:
```javascript

var models = require('express-cassandra');

exports.postStatus = function(req, res){
    var email = req.body.email,
        profile_photo = req.user.profile_photo,
        firstname = req.user.firstname,
        lastname = req.user.lastname,
        status = req.body.status,
        followers = req.followers,
        status_id = models.timeuuid();

    var queries = [
        {
            query: "INSERT INTO parent_status_updates (email, id, body) VALUES (?, ?, ?)",
            params: [email, status_id, status]
        }
    ];

    for(var i=0; i<followers.length; i++){
        var query = {
            query: "INSERT INTO home_status_updates (timeline_email, status_update_id, body, status_update_email, profile_photo, status_update_firstname, status_update_lastname) VALUES (?, ?, ?, ?, ?, ?, ?)",
            params: [followers[i], status_id, status, email, profile_photo, firstname, lastname]
        }
        queries.push(query);
    }

    models.instance.parent_status_updates.get_cql_client(function(err, client){
        client.batch(queries, { prepare: true }, function(err) {
            if(err){
                return res.json({"status": "failed"})
            }
        });
    });
```
I was previously using the save function, but I realized that I needed to use a batch query to ensure an atomic write. Regardless, the null error issue still occurs both ways.

**Comment by masumsoft** [comment]
@VipulSarin The code you've posted actually works pretty well. I've tested it in my workstation. Also it is actually using the official cql driver's batch query interface. I can't see why changing the apollo_schemer.js would affect this in any way! Are you sure your posted code does not work without that apollo_schemer hack?

**Comment by VipulSarin** [comment]
I just removed the hack in apollo_schemer and gave it a shot. I got the same null error :( . In fact I printed out the output schema from apollo_schemer.js: 
```javascript
var output_schema = lodash.clone(model_schema,true);
console.log("Lodash output schema = "+JSON.stringify(output_schema))
```
and this is the output: 
Lodash output schema = {"fields":{"timeline_email":{"type":"text"},"status_update_id":{"type":"timeuuid"},"body":{"type":"text"},"status_update_email":{"type":"text"},"status_update_firstname":{"type":"text"},"status_update_lastname":{"type":"text"},"profile_photo":{"type":"text"}},"key":[["timeline_email"],"status_update_id"],"indexes":["status_update_email"]}

Lodash output schema = {"fields":{"body":"text","profile_photo":"text","status_update_email":"text","status_update_firstname":"text",**"status_update_id":null,**"status_update_lastname":"text","timeline_email":"text"},"indexes":["status_update_email"],"key":[["timeline_email"],"status_update_id"]}

Notice the status_update_id is returned as null from Lodash in the second statement. 

I can't understand why it's happening for me and not you. Since you've got test cases to check this (and they pass), I am inclined to think that the error is something on my end.
When I have some free time, I'll dig deeper into this and see why its happening for me.
Feel free to close the issue, since your not able to recreate it.
BTW - excellent library! Its met almost all my other needs almost perfectly! Thank you very much.

**Comment by masumsoft** [comment]
Thanks for the appreciation. I'm also skeptical about the issue. I've already tried several ways to reproduce the issue without luck. It might also be a special case happening with you that I'm missing in my tests. I'll look into it again in more detail to see if I can find the problem. 

Also from your use case, I feel it would be a nice thing if the orm supported batch queries. Right now to do batch queries you had to manually build the queries. So I'm thinking of supporting batches directly as an orm feature.

**Comment by VipulSarin** [comment]
Batch queries would be a great feature to have, since with Cassandra denormalization of data is required for efficient querying and therefore writes to multiple tables must be made atomically.

**Comment by masumsoft** [comment]
Batch operations against the save, update and delete ORM functions are now supported, details available in ReadMe: https://github.com/masumsoft/express-cassandra#batching-orm-operations
