### ISSUE TITLE
Update with value equals `null`

### ISSUE THREAD

**Issue by aleksandrsorokin** [masumsoft/express-cassandra#71]
I think there is error in next expression:
https://github.com/masumsoft/express-cassandra/blob/master/src/orm/base_model.js#L1637

If value will be `null` it's generate error (typeof `null` === `object`):
`TypeError: Cannot read property '$add' of null`.

**Comment by masumsoft** [comment]
@aleksandrsorokin the latest v1.4.2 contains fixes for this kind of problems.

**Comment by aleksandrsorokin** [comment]
@masumsoft thank you!

I think that setting datatypes.unset and undefined as field value doesn't unset field value. I tried to use this as alternative, but it did not unset filed values. I can provide example later.

**Comment by masumsoft** [comment]
datatypes.unset will not clear field value, it is used to tell cassandra to ignore it instead of creating an unnecessary tombstone. You should use `null` if you need to delete/clear a field value.

**Comment by masumsoft** [comment]
I've now updated the relevant doc to clarify the confusion, hope this will help:

https://github.com/masumsoft/express-cassandra/blob/master/docs/datatypes.md#null-and-unset-values
