### ISSUE TITLE
User-provided options array overrides default options completely for batch updates

### ISSUE THREAD

**Issue by pierreis** [masumsoft/express-cassandra#77]
Currently, setting the `options` parameter of the `doBatch()` function – for example to set the batch as a counter batch (which requires `{ counter: true }` [_BTW, might be useful to point out in the docs, it gave me a bit of a headache_]) – overrides completely ORM default request preparation.

The docs says:

```
All queries except schema definition related queries (i.e. create table etc.) are
prepared by default. If you don't want to prepare queries, just set prepare=false
in the options object.
```

Considering that, I would expect that unless explicitly setting the prepare parameter to false, the request would be prepared by default.

**Comment by masumsoft** [comment]
Fixed in version 1.6.4

**Comment by pierreis** [comment]
Great job, thanks!
Keep up the good work, this project really is awesome.

**Comment by popcornAC** [comment]
Hey can someone provide an example of doing a batch query (async or not) for a counter table? Having a lot of trouble implementing this and I can't find the documentation for it.
