### ISSUE TITLE
Unable to do multiple connections

### ISSUE THREAD

**Issue by hwernstrom** [masumsoft/express-cassandra#8]
I have been unable to do multiple connections. I've done a fix at hwernstrom/express-cassandra.

**Comment by hwernstrom** [comment]
That is not quite a fix. It will connect to 2 different keyspaces but won't create all tables in both keyspaces.

**Comment by masumsoft** [comment]
Could you please elaborate on the purpose of supporting multiple connections? Also did you mean supporting multiple connections to cassandra or supporting multiple keyspaces from the same application?

**Comment by hwernstrom** [comment]
I'm trying to connect to two different key spaces in the same cluster from the same app. One is a manager and the other is a key spaces setup for each client.
Thanks

**Comment by masumsoft** [comment]
#21 fixes this issue

**Comment by luvsaxenawinzo** [comment]
Are we able to make connections to multiple keyspaces ?
