### ISSUE TITLE
ExpressCassandraClient not able to connect DB

### ISSUE THREAD

**Issue by sudheerj** [masumsoft/express-cassandra#82]
When I try to connect Cassandra DB i got below exception

> Could not connect to Cassandra: Keyspace system_schema does not exist

Express-cassandra: 1.6.2
Cassandra: 2.1.15

**Comment by masumsoft** [comment]
This module requires that you use casandra 3.x. If you want to use 2.x, then you have to use an older version of the module. Please refer to the instsallation guide for details: https://github.com/masumsoft/express-cassandra#installation

**Comment by sudheerj** [comment]
Thanks masumsoft. I figured out the above issue.
