### ISSUE TITLE
Type required for list/array of Objects

### ISSUE THREAD

**Issue by sudheerj** [masumsoft/express-cassandra#84]
I'am trying to use express-cassandra ORM for the application.But I just want to know how we can store list/array of objects to store column value as below

> [ { "ibx_code" : "LA1", "_id" : "cid-52367986" },{ "ibx_code" : "SV2", "_id" : "cid-52367916" }]

Thanks for the help in advance.

**Comment by masumsoft** [comment]
http://express-cassandra.readthedocs.io/en/latest/advanced/#collection-data-types

**Comment by sudheerj** [comment]
Thanks I read the documentation already.I'am looking for list of JS/JSON objects.But I'am not sure what will fit for **typeDef** to define JS/JSON object.

**Comment by masumsoft** [comment]
You may use `typeDef: map<text, text>` or something similar. I guess you need to read the cassandra doc regarding collection data types: http://docs.datastax.com/en/cql/3.3/cql/cql_using/useCollections.html

**Comment by sudheerj** [comment]
Map<text,text> is useful for the single JS object.Actually I need to represent array of objects.

> [ { "ibx_code" : "LA1", "_id" : "cid-52367986" },{ "ibx_code" : "SV2", "_id" : "cid-52367916" }]
