### ISSUE TITLE
IN predicates on non-primary-key columns not supported

### ISSUE THREAD

**Issue by sudheerj** [masumsoft/express-cassandra#85]
When I try to execute IN class on table fields then below exception is thrown.But as per documentation it should work [http://express-cassandra.readthedocs.io/en/latest/find/](url)

> error: Resolve function failed error=apollo.model.find.dberror: Error during find query on DB -> ResponseError: IN predicates on non-primary-key columns (account_number) is not yet supported

Thanks in advance for the help.

**Comment by masumsoft** [comment]
Doing this is not supported by cassandra. The documentation clearly mentions this in the link you've provided:

> You cannot, for example, use $in operator for a key which is not part of the primary key. Querying in Cassandra is very basic but could be confusing at first. 

Reading the documentation properly before creating issues would be more appreciated. Also a basic understanding of cassandra and the limitations imposed by the database is also required if you want to use it for anything serious.
