### ISSUE TITLE
ORDER BY is only supported when the partition key is restricted by an EQ or an IN.

### ISSUE THREAD

**Issue by sudheerj** [masumsoft/express-cassandra#86]
If I try to add ORDER BY operator for table fields the below exception is thrown

> error: Resolve function failed error=apollo.model.find.dberror: Error during find query on DB -> ResponseError: ORDER BY is only supported when the partition key is restricted by an EQ or an IN.

Can you please let us know why this issue occurred.Thanks in advance.

**Comment by masumsoft** [comment]
order by queries must be cassandra compliant. You cannot do order by on arbitrary columns. Cassandra and Google BigTable architecture is fundamentally different than other database systems. You have to design your table schema based on the queries you would do on that schema. If you want to do order by, the field must be part of the clustering columns and you must specify the partition key in your where clause. 

Cassandra docs has detailed description about it. You may want to have a look at the following links:

http://docs.datastax.com/en/cql/3.3/cql/cql_using/useCompositePartitionKeyConcept.html
http://docs.datastax.com/en/cql/3.3/cql/cql_using/useCompoundPrimaryKeyConcept.html
https://docs.datastax.com/en/cql/3.3/cql/ddl/dataModelingApproach.html
http://docs.datastax.com/en/cql/3.3/cql/cql_using/useCreateMV.html
