### ISSUE TITLE
there is no way to truncate a cassandra table

### ISSUE THREAD

**Issue by fadyZohdy** [masumsoft/express-cassandra#88]

**Comment by masumsoft** [comment]
Truncate is destructive and a rarely used operation that should ideally be performed from cqlsh. Whether an ORM should support this natively is a debatable question. What is your argument for supporting truncate in the ORM? Could you provide a real use case for this?

Btw you could always use the [raw query interface](http://express-cassandra.readthedocs.io/en/latest/notes/#raw-query) to do it:

```js
var query = "truncate table person";
models.instance.Person.execute_query(query, [], function(err){
    // your table is now truncated
});
```

**Comment by fadyZohdy** [comment]
I needed it for testing mainly to empty the table before and after the testing suite instead of creating and dropping the table every time.

**Comment by masumsoft** [comment]
Okay, it's done. Truncate is now supported by the commit a5d257582eb82e0e61f1ad09698781289dc22b27

Published into npm v1.7.2

**Comment by masumsoft** [comment]
Usage Doc: https://github.com/masumsoft/express-cassandra/blob/master/docs/management.md#truncate

**Comment by fadyZohdy** [comment]
That was quick :D Thanx
