### ISSUE TITLE
Not able to pass page state 'pageState' in find query

### ISSUE THREAD

**Issue by senthilkumar-sh** [masumsoft/express-cassandra#89]
I am trying to pass the pageState to maintain my current pagination page. I am unable to pass the value in my find query.

Here is my find Query :

models.instance.Person.eachRow({pageState: 2, allow_filtering: true, autoPage : true, fetchSize : 10}, function(n, row){

Error:

{ apollo.model.find.dberror: Error during find query on DB -> TypeError: "list" argument must be an Array of Buffers

and in the result i always get 'pageState: null'

Please fix this or let me know is there any other way to solve this

**Comment by masumsoft** [comment]
Looks like you are providing the options object in the query parameter. Are you following the docs properly? Here is an example if you need a blank query:

```js
models.instance.Person.eachRow({}, {pageState: 2, allow_filtering: true, autoPage : true, fetchSize : 10}, function(n, row){
    // invoked per each row in all the pages
}, function(err, result){
    // ...
});
```
