### ISSUE TITLE
Pagination with order by 

### ISSUE THREAD

**Issue by JayeshLunkad** [masumsoft/express-cassandra#90]
Hi i want to perform pagination on record retrieved from Cassandra db along with sorting. How can i achieve this using express cansandra.

Thanks 
Jayesh

**Comment by masumsoft** [comment]
If you are using the default unordered partitioner, then "order by" is supported by cassandra on clustering columns only. If you want pagination on clustering columns, you could use $gt or $lt with the last item returned in your previous page depending on the clustering order defined.
